param(
    [ValidateSet("Debug", "Release")]
    [string]$Configuration = "Release",

    [ValidateSet("x64", "ARM64")]
    [string]$Platform = "x64",

    [switch]$SkipInf2Cat
)

$ErrorActionPreference = "Stop"
Import-Module (Join-Path $PSScriptRoot "OpenA8DJ.WindowsCommon.psm1") -Force

$repoRoot = Resolve-Path (Join-Path $PSScriptRoot "..\..")
$solution = Join-Path $repoRoot "windows\OpenA8DJWindows.sln"
$driverDir = Join-Path $repoRoot "windows\driver"
$distDir = Join-Path $repoRoot "windows\dist\$Configuration\$Platform"
$infSource = Join-Path $driverDir "OpenA8DJUsb.inf"
$infDest = Join-Path $distDir "OpenA8DJUsb.inf"
$identityHeader = Join-Path $driverDir "OpenA8DJBuildIdentity.h"
$objDir = Join-Path $repoRoot "windows\obj\$Configuration\$Platform\OpenA8DJUsb"

$fingerprintInputs = @(
    "windows/driver/OpenA8DJUsb.c",
    "windows/driver/OpenA8DJUsb.h",
    "windows/driver/OpenA8DJUsb.inf",
    "windows/include/OpenA8DJShared.h",
    "windows/driver/OpenA8DJUsb.vcxproj"
)
$fingerprintText = foreach ($relative in $fingerprintInputs) {
    $path = Join-Path $repoRoot ($relative -replace '/', '\')
    "---$relative---`n" + ((Get-Content -LiteralPath $path -Raw) -replace "`r`n", "`n")
}
$fingerprintBytes = [Text.Encoding]::UTF8.GetBytes(($fingerprintText -join "`n"))
$sha = [Security.Cryptography.SHA256]::Create()
try {
    $buildFingerprint = ([BitConverter]::ToString($sha.ComputeHash($fingerprintBytes))).Replace('-', '').ToLowerInvariant()
} finally {
    $sha.Dispose()
}
@(
    '#pragma once',
    '',
    '/* Generated by windows/scripts/build-driver.ps1. */',
    "#define OPENA8DJ_BUILD_FINGERPRINT `"$buildFingerprint`""
) | Set-Content -LiteralPath $identityHeader -Encoding ASCII

# A physical candidate must never inherit a prior .sys, .pdb, INF, or catalog.
foreach ($cleanPath in @($distDir, $objDir)) {
    if (Test-Path -LiteralPath $cleanPath) {
        Remove-Item -LiteralPath $cleanPath -Recurse -Force
    }
}

function Find-MsBuild {
    $vswhere = Join-Path ${env:ProgramFiles(x86)} "Microsoft Visual Studio\Installer\vswhere.exe"
    if (Test-Path $vswhere) {
        $path = & $vswhere -latest -requires Microsoft.Component.MSBuild -find "MSBuild\Current\Bin\amd64\MSBuild.exe" | Select-Object -First 1
        if ($path) {
            return $path
        }
    }

    $fallback = Join-Path ${env:ProgramFiles(x86)} "Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\amd64\MSBuild.exe"
    if (Test-Path $fallback) {
        return $fallback
    }

    throw "MSBuild was not found. Install Visual Studio 2022 Build Tools with the Windows Driver Kit."
}

function Find-Inf2Cat {
    $kitsRoot = Join-Path ${env:ProgramFiles(x86)} "Windows Kits\10\bin"
    if (-not (Test-Path $kitsRoot)) {
        throw "Windows Kits bin directory was not found. Install the Windows SDK and WDK."
    }

    $candidate = Get-ChildItem -Path $kitsRoot -Directory |
        Sort-Object Name -Descending |
        ForEach-Object {
            Join-Path $_.FullName "x64\Inf2Cat.exe"
            Join-Path $_.FullName "x86\Inf2Cat.exe"
        } |
        Where-Object { Test-Path $_ } |
        Select-Object -First 1

    if (-not $candidate) {
        throw "Inf2Cat.exe was not found. Install the Windows Driver Kit."
    }

    return $candidate
}

function Find-InfVerif {
    $toolsRoot = Join-Path ${env:ProgramFiles(x86)} "Windows Kits\10\Tools"
    if (-not (Test-Path $toolsRoot)) {
        throw "Windows Kits tools directory was not found. Install the Windows SDK and WDK."
    }

    $candidate = Get-ChildItem -Path $toolsRoot -Directory |
        Sort-Object Name -Descending |
        ForEach-Object {
            Join-Path $_.FullName "x64\infverif.exe"
            Join-Path $_.FullName "arm64\infverif.exe"
        } |
        Where-Object { Test-Path $_ } |
        Select-Object -First 1

    if (-not $candidate) {
        throw "infverif.exe was not found. Install the Windows SDK and WDK."
    }

    return $candidate
}

function Find-SignTool {
    $kitsRoot = Join-Path ${env:ProgramFiles(x86)} "Windows Kits\10\bin"
    if (-not (Test-Path $kitsRoot)) {
        throw "Windows Kits bin directory was not found. Install the Windows SDK and WDK."
    }

    $candidate = Get-ChildItem -Path $kitsRoot -Directory |
        Sort-Object Name -Descending |
        ForEach-Object {
            Join-Path $_.FullName "x64\signtool.exe"
            Join-Path $_.FullName "x86\signtool.exe"
        } |
        Where-Object { Test-Path $_ } |
        Select-Object -First 1

    if (-not $candidate) {
        throw "signtool.exe was not found. Install the Windows SDK and WDK."
    }
    return $candidate
}

$msbuild = Find-MsBuild

Write-Host "Building $solution ($Configuration|$Platform)"
& $msbuild $solution /m /restore /p:Configuration=$Configuration /p:Platform=$Platform
if ($LASTEXITCODE -ne 0) {
    throw "MSBuild failed with exit code $LASTEXITCODE"
}

New-Item -ItemType Directory -Path $distDir -Force | Out-Null
Copy-Item $infSource $infDest -Force
Get-ChildItem -Path $distDir -Filter "*.ilk" -ErrorAction SilentlyContinue | Remove-Item -Force

$sysPath = Join-Path $distDir "OpenA8DJUsb.sys"
if (-not (Test-Path $sysPath)) {
    throw "Expected driver output not found: $sysPath"
}

# The WDK project exports the public test certificate using the project name,
# while every physical-load path consumes the explicit TestCertificate alias.
# Bind the alias to the actual SYS signer before it can enter the catalog or
# package manifest so a stale or unrelated certificate can never be trusted.
$sysSignature = Get-AuthenticodeSignature -LiteralPath $sysPath
if ($sysSignature.Status -ne 'Valid' -or $null -eq $sysSignature.SignerCertificate) {
    throw "The built SYS is not validly signed; refusing to package it."
}
$wdkCertificatePath = Join-Path $distDir "OpenA8DJUsb.cer"
$testCertificatePath = Join-Path $distDir "OpenA8DJUsb-TestCertificate.cer"
if (-not (Test-Path -LiteralPath $wdkCertificatePath)) {
    throw "The WDK did not export the SYS test certificate: $wdkCertificatePath"
}
$wdkCertificate = [Security.Cryptography.X509Certificates.X509Certificate2]::new($wdkCertificatePath)
if ($wdkCertificate.Thumbprint -ine $sysSignature.SignerCertificate.Thumbprint) {
    throw "Exported certificate does not match the SYS signer; refusing to package it."
}
Copy-Item -LiteralPath $wdkCertificatePath -Destination $testCertificatePath -Force

$infVerif = Find-InfVerif
Write-Host "Validating INF with InfVerif: $infDest"
& $infVerif /w /v $infDest
if ($LASTEXITCODE -ne 0) {
    throw "InfVerif Windows-driver validation failed with exit code $LASTEXITCODE"
}
& $infVerif /h /v $infDest
if ($LASTEXITCODE -ne 0) {
    throw "InfVerif hardware-signature validation failed with exit code $LASTEXITCODE"
}

if (-not $SkipInf2Cat) {
    $inf2cat = Find-Inf2Cat
    $osTargets = if ($Platform -eq "ARM64") {
        "10_VB_ARM64,10_CO_ARM64,10_GE_ARM64"
    } else {
        "10_VB_X64,10_CO_X64,10_GE_X64"
    }

    Write-Host "Generating catalog with Inf2Cat for $osTargets"
    & $inf2cat /driver:$distDir /os:$osTargets /verbose
    if ($LASTEXITCODE -ne 0) {
        throw "Inf2Cat failed with exit code $LASTEXITCODE"
    }

    $catPath = Join-Path $distDir "opena8djusb.cat"
    $signTool = Find-SignTool
    Write-Host "Signing catalog with the SYS test certificate"
    & $signTool sign /v /fd SHA256 /sha1 $sysSignature.SignerCertificate.Thumbprint $catPath
    if ($LASTEXITCODE -ne 0) {
        throw "Catalog signing failed with exit code $LASTEXITCODE"
    }
    foreach ($signedPath in @($sysPath, $catPath)) {
        & $signTool verify /pa $signedPath
        if ($LASTEXITCODE -ne 0) {
            throw "Signature verification failed for $signedPath with exit code $LASTEXITCODE"
        }
    }
}

$manifestPath = New-OpenA8DJPackageManifest `
    -PackageDir $distDir `
    -Configuration $Configuration `
    -Platform $Platform `
    -BuildFingerprint $buildFingerprint

Write-Host "Windows driver package staged in $distDir"
Write-Host "Build fingerprint: $buildFingerprint"
Write-Host "Package manifest: $manifestPath"
