PROJECT := opena8dj
VERSION := 0.5.1
TOOL := build/opena8dj-probe
SRC := src/opena8dj-probe.m
HAL_BUNDLE := build/OpenA8DJ.driver
HAL_BIN := $(HAL_BUNDLE)/Contents/MacOS/OpenA8DJHAL
HAL_FLAGS_STAMP := build/.hal-cflags.stamp
USB_PLAY_FLAGS_STAMP := build/.usb-play-cflags.stamp
HAL_BASE_SRC := src/hal/OpenA8DJHAL.c src/hal/OpenA8DJUSB.m
HAL_PREPARED_RUNTIME_SRC := \
	src/hal/OpenA8DJPreparedRuntimeBridge.mm \
	core/src/usb_submit_plan.cpp \
	core/src/usb_request_pool.cpp \
	core/src/prepared_usb_async_runtime.cpp
HAL_PREPARED_OBJ_DIR := build/hal-prepared-runtime-obj
HAL_SRC := $(HAL_BASE_SRC)
HAL_PLIST := resources/OpenA8DJ.driver/Contents/Info.plist
HAL_SMOKE := build/hal-smoke
HAL_SMOKE_SRC := src/tools/hal-smoke.c
HAL_PARITY_SMOKE := build/hal-parity-smoke
HAL_PARITY_SMOKE_SRC := src/tools/hal-parity-smoke.c
AUDIO_LIST := build/audio-list
AUDIO_LIST_SRC := src/tools/audio-list.c
AUDIO_INSPECT := build/audio-inspect
AUDIO_INSPECT_SRC := src/tools/audio-inspect.c
AUDIO_IO_TEST := build/audio-io-test
AUDIO_IO_TEST_SRC := src/tools/audio-io-test.c
AUDIO_WAV_PLAY := build/audio-wav-play
AUDIO_WAV_PLAY_SRC := src/tools/audio-wav-play.c
AUDIO_RECORD := build/audio-record
AUDIO_RECORD_SRC := src/tools/audio-record.c
AUDIO_CONFIG := build/audio-config
AUDIO_CONFIG_SRC := src/tools/audio-config.c
AUDIO_DEFAULT := build/audio-default
AUDIO_DEFAULT_SRC := src/tools/audio-default.c
AUDIO_PAIR_TONE := build/audio-pair-tone
AUDIO_PAIR_TONE_SRC := src/tools/audio-pair-tone.c
AUDIO_ROUTE := build/audio-route
AUDIO_ROUTE_SRC := src/tools/audio-route.c
INPUT_METER := build/audio-input-meter
INPUT_METER_SRC := src/tools/audio-input-meter.c
MACBOOK_MIC_RECORD := build/macbook-mic-record
MACBOOK_MIC_RECORD_SRC := src/tools/macbook-mic-record.c
USB_PLAY := build/opena8dj-usb-play
USB_PLAY_SRC := src/tools/opena8dj-usb-play.m
USB_PLAY_PLAIN := build/opena8dj-usb-play-plain
USB_PLAY_PLAIN_GAIN05 := build/opena8dj-usb-play-plain-gain05
USB_INPUT_METER := build/opena8dj-usb-input-meter
USB_INPUT_METER_SRC := src/tools/opena8dj-usb-input-meter.m
MIDI_BRIDGE := build/opena8dj-midid
MIDI_BRIDGE_SRC := src/tools/opena8dj-midid.m
CONTROL_TOOL := build/opena8dj-control
CONTROL_TOOL_SRC := src/tools/opena8dj-control.c
CONTROL_CENTER_APP := build/OpenA8DJControlCenter.app
CONTROL_CENTER_SRC := macos/OpenA8DJControlCenter/OpenA8DJControlCenter.swift
CONTROL_CENTER_PLIST := macos/OpenA8DJControlCenter/Info.plist
MIDI_LIST := build/midi-list
MIDI_LIST_SRC := src/tools/midi-list.c
PHYSICAL_RUN_COMPARE := build/physical-run-compare
PHYSICAL_RUN_COMPARE_SRC := tools/physical_run_compare.cpp
LAUNCH_AGENT_PLIST := resources/org.opena8dj.midid.plist
PKG_ROOT := build/pkgroot
PKG_COMPONENTS := build/components.plist
PKG_SCRIPTS := resources/pkg/scripts
PKG_SANITIZER := scripts/sanitize-macos-pkg.sh
PKG := build/OpenA8DJ-$(VERSION).pkg
CONTROL_PKG_ROOT := build/control-pkgroot
CONTROL_PKG_COMPONENTS := build/control-components.plist
CONTROL_PKG_SCRIPTS := resources/control-surfaces-pkg/scripts
CONTROL_PKG := build/opena8dj-tools-$(VERSION).pkg
DMG_ROOT := build/dmgroot
DMG := build/OpenA8DJ-$(VERSION).dmg
DMG_README := resources/dmg/README.txt
CONTROL_DMG_ROOT := build/control-dmgroot
CONTROL_DMG := build/opena8dj-tools-$(VERSION).dmg
CONTROL_DMG_README := resources/control-surfaces-dmg/README.txt
CHECKSUMS := build/OpenA8DJ-$(VERSION)-checksums.txt
RELEASE_NOTES := docs/reference/release-notes-$(VERSION).md
SIGN_IDENTITY ?= -
PKG_SIGN_IDENTITY ?=
DMG_SIGN_IDENTITY ?=
NOTARY_PROFILE ?= OpenA8DJNotary
CODESIGN_TIMESTAMP ?= --timestamp=none
CODESIGN_OPTIONS ?=
HAL_STAPLE_AFTER_SIGN ?= 0
HAL_DIAGNOSTIC ?= 0
HAL_DIAGNOSTIC_DIR_DEFAULT ?= /tmp
HAL_OUTPUT_GAIN ?= 0.75f
HAL_PRIMARY_OUTPUT_PAIR ?= 0
HAL_OUTPUT_PREFETCH_FRAMES ?= 128
HAL_INPUT_DECODE ?= 1
HAL_TIMECODE_INPUT_GAIN ?= 1.0f
HAL_TIMECODE_INPUT_GATE_THRESHOLD ?= 0.0f
HAL_TIMECODE_INPUT_GATE_HOLD_FRAMES ?= 0
HAL_INPUT_SPSC_RING ?= 0
HAL_INPUT_DECODE_ACTIVE_GATING ?= 1
HAL_INPUT_MAX_LATENCY_FRAMES ?= 0
HAL_INPUT_IO ?= 1
HAL_OUTPUT_ONLY_NO_CAPTURE_ISOC ?= 0
HAL_OUTPUT_FIFO ?= 0
HAL_INPUT_STREAMS ?= 1
HAL_INPUT_CHECKS ?= 0
HAL_OUTPUT_STREAMS ?= 4
HAL_ISO_FRAMES ?= 64
HAL_PLAYBACK_ISO_FRAMES ?= $(HAL_ISO_FRAMES)
HAL_CAPTURE_ISO_FRAMES ?= $(HAL_ISO_FRAMES)
HAL_CAPTURE_QUEUE ?= 8
HAL_PLAYBACK_QUEUE ?= 8
HAL_PLAYBACK_CAPTURE_PACED ?= 1
HAL_CAPTURE_PACED_OUT_LEAD ?= 2
HAL_CAPTURE_PACED_PLAYBACK_REFILL ?= 0
HAL_PLAYBACK_COALESCE_TRANSFERS ?= 1
HAL_PREPARED_USB_SUBMIT_RUNTIME ?= 0
HAL_PREPARED_USB_PLAYBACK_ONLY_RUNTIME ?= 0
HAL_PREPARED_USB_SLOTS_PER_SUBMIT ?= 8
HAL_QUEUE_PLAYBACK_BEFORE_CAPTURE_REQUEUE ?= 0
HAL_USB_CLOCK_ANCHOR ?= 0
HAL_USB_STABLE_FRAME ?= 0
HAL_USB_ZERO_TIMESTAMP ?= 0
HAL_USB_ANCHOR_FILTER ?= 8
HAL_EXPLICIT_SCHED ?= 0
HAL_EXPLICIT_SCHED_FAIL_FALLBACK ?= 0
HAL_ELASTIC_OUTPUT ?= 0
HAL_OUTPUT_NATIVE ?= 0
HAL_FAST_OUTPUT_QUANTIZER ?= 0
HAL_FAST_OUTPUT_PREFETCH_CLEAR ?= 1
HAL_UNROLLED_OUTPUT_PACK ?= 1
HAL_STREAM_USAGE ?= 1
HAL_TRANSFER_POOL ?= 1
HAL_STRICT_TRANSFER_POOL ?= 0
HAL_TRANSFER_POOL_CURSOR ?= 1
HAL_REUSE_ISOC_COMPLETIONS ?= 0
HAL_RAW_ISOC_COMPLETIONS ?= 0
HAL_LEGACY_OUT_SLOTS ?= 0
HAL_USB_QUEUE_QOS ?= 0
HAL_FAST_ISO_TRANSFER_CONFIG ?= 1
HAL_TRANSFER_LEDGER ?= 0
HAL_PLAYBACK_PAYLOAD_GUARD ?= 0
HAL_OUTPUT_SAMPLE_TIME_FOLLOWER ?= 0
HAL_IGNORE_OUTPUT_SAMPLE_TIME ?= 1
HAL_FLUSH_OUTPUT_IN_WRITE_MIX ?= 0
HAL_FLUSH_TOUCHED_OUTPUT ?= 0
HAL_CADENCE_DIAGNOSTIC ?= 0
HAL_STREAM_KEEPALIVE ?= 0
HAL_STRICT_IDLE_SILENCE ?= 1
HAL_IDLE_PLAYBACK_GATE ?= 1
HAL_IDLE_PLAYBACK_GATE_THRESHOLD ?= 0.000001f
HAL_IDLE_PLAYBACK_GATE_HOLD_FRAMES ?= 0
HAL_OUTPUT_ZERO_FLOOR ?= 0.0f
HAL_OUTPUT_START_LATENCY_FRAMES ?= 3072
HAL_OUTPUT_RESTART_LATENCY_FRAMES ?= 1536
HAL_OUTPUT_TARGET_LATENCY_FRAMES ?= 3072
HAL_OUTPUT_ELASTIC_HIGH_WATER_FRAMES ?= 9216
HAL_OUTPUT_AMPLITUDE_STATS ?= 0
HAL_OUTPUT_WRITE_STATS ?= 0
HAL_HOT_STREAM_STATS ?= 0
HAL_HOT_PATH_TIMING ?= 0
HAL_TRACE ?= 0
HAL_HOT_STREAM_STATS_INTERVAL ?= 16
HAL_STREAM_STATS_ATOMIC_ACCUMULATORS ?= 0
HAL_PROPERTY_BACKOFF_USEC ?= 0
HAL_OUTPUT_START_BYTE ?= 4
HAL_OUTPUT_CHECK_OFFSET ?= 8
HAL_VALID_CAPTURE_OUT_LAYOUT ?= 0
HAL_SELECT_ALT0_BEFORE_ALT1 ?= 0
HAL_BACKGROUND_WARM_OPEN ?= 0
HAL_BACKGROUND_PREOPEN_ON_INIT ?= 1
HAL_INVERT_OUTPUT_RIGHT ?= 0
HAL_STOP_GRACE_USEC ?= 10000000
HAL_STOP_ISOC_ON_STOP ?= 1
HAL_RESET_AUDIO_PARAMS_BEFORE_STREAM ?= 0
HAL_AUDIO_PARAMS_RESET_WAIT_FOR_REPLY ?= 0
HAL_AUDIO_PARAMS_RESET_SETTLE_USEC ?= 0
HAL_CLOCK_DRIFT_TOLERANCE ?= 0
SOUNDCHECK_MUSIC ?=
SOUNDCHECK_MUSIC_DIR ?= $(HOME)/Music
SOUNDCHECK_CAPTURE ?=
SOUNDCHECK_CAPTURE_CHANNELS ?= 1,2
SOUNDCHECK_PAIR ?= A
SOUNDCHECK_RATE ?= 48000
SOUNDCHECK_BUFFER ?= 512
SOUNDCHECK_SECONDS ?= 20
SOUNDCHECK_PREFLIGHT_SECONDS ?= 5
SOUNDCHECK_MODE ?= dense
SOUNDCHECK_PREFLIGHT_MODE ?= start
SOUNDCHECK_TARGET_PEAK_DB ?= -16
SOUNDCHECK_CPU_STRESS ?= 0
SOUNDCHECK_CPU_STRESS_AFTER ?= 5
SOUNDCHECK_CPU_STRESS_SECONDS ?= 8
SOUNDCHECK_CPU_STRESS_WORKERS ?= auto
DIRECT_USB_LEAD_FRAMES ?= 8192
DIRECT_USB_PLAYER ?= build/opena8dj-usb-play
SOUNDCHECK_MIN_ALIGNMENT ?= 0.98
SOUNDCHECK_MIN_SNR_DB ?= 35.0
SOUNDCHECK_MAX_CLICKS ?= 10
SOUNDCHECK_MAX_LAG_JUMPS ?= 0
SOUNDCHECK_MAX_MID_BAND_RESIDUAL_RATIO ?= 0.04
SOUNDCHECK_MAX_HIGH_BAND_RESIDUAL_RATIO ?= 0.08
SOUNDCHECK_MAX_QUIET_MID_BAND_NOISE_DBFS ?= -58.0
SOUNDCHECK_MAX_MID_BAND_CPU_CORR ?= 0.60
SOUNDCHECK_IRIG_PAIR ?= B
SOUNDCHECK_IRIG_MODE ?= start
SOUNDCHECK_IRIG_SECONDS ?= 8
SOUNDCHECK_IRIG_MIN_ALIGNMENT ?= 0.93
SOUNDCHECK_IRIG_MIN_SNR_DB ?= 8.0
SOUNDCHECK_IRIG_MAX_CLICKS ?= 500
SOUNDCHECK_IRIG_MAX_LAG_JUMPS ?= 64
SOUNDCHECK_IRIG_MAX_MID_BAND_RESIDUAL_RATIO ?= 1.65
SOUNDCHECK_IRIG_MAX_HIGH_BAND_RESIDUAL_RATIO ?= 1.50
SOUNDCHECK_IRIG_MAX_QUIET_MID_BAND_NOISE_DBFS ?= -38.0
SOUNDCHECK_IRIG_MAX_MID_BAND_CPU_CORR ?= 0.65
CHANNEL_MATRIX_PAIR ?= A
CHANNEL_MATRIX_RATE ?= 48000
CHANNEL_MATRIX_SECONDS ?= 8
CHANNEL_MATRIX_PEAK ?= 0.30
SIM_OUTPUT_SECONDS ?= 3
SIM_OUTPUT_MODE ?= dense
SIM_OUTPUT_PAIR ?= A
SIM_OUTPUT_GAIN ?= 0.5

CC := xcrun clang
HAL_LD := xcrun clang
CFLAGS := -fobjc-arc -Wall -Wextra -Wpedantic -O2
HAL_CFLAGS := -fobjc-arc -Wall -Wextra -Wpedantic -O2 -DOPENA8DJ_ENABLE_DIAGNOSTIC_CAPTURE=$(HAL_DIAGNOSTIC) -DOPENA8DJ_OUTPUT_GAIN=$(HAL_OUTPUT_GAIN) -DOPENA8DJ_PRIMARY_OUTPUT_PAIR=$(HAL_PRIMARY_OUTPUT_PAIR) -DOPENA8DJ_OUTPUT_PREFETCH_FRAMES=$(HAL_OUTPUT_PREFETCH_FRAMES) -DOPENA8DJ_ENABLE_INPUT_DECODE=$(HAL_INPUT_DECODE) -DOPENA8DJ_INPUT_SPSC_RING=$(HAL_INPUT_SPSC_RING) -DOPENA8DJ_INPUT_DECODE_ACTIVE_GATING=$(HAL_INPUT_DECODE_ACTIVE_GATING) -DOPENA8DJ_INPUT_MAX_LATENCY_FRAMES=$(HAL_INPUT_MAX_LATENCY_FRAMES) -DOPENA8DJ_ENABLE_INPUT_IO=$(HAL_INPUT_IO) -DOPENA8DJ_OUTPUT_ONLY_NO_CAPTURE_ISOC=$(HAL_OUTPUT_ONLY_NO_CAPTURE_ISOC) -DOPENA8DJ_INPUT_STREAM_COUNT=$(HAL_INPUT_STREAMS) -DOPENA8DJ_ENABLE_INPUT_CHECKS=$(HAL_INPUT_CHECKS) -DOPENA8DJ_OUTPUT_STREAM_COUNT=$(HAL_OUTPUT_STREAMS) -DOPENA8DJ_ISO_FRAMES_PER_TRANSFER=$(HAL_ISO_FRAMES) -DOPENA8DJ_PLAYBACK_ISO_FRAMES_PER_TRANSFER=$(HAL_PLAYBACK_ISO_FRAMES) -DOPENA8DJ_CAPTURE_ISO_FRAMES_PER_TRANSFER=$(HAL_CAPTURE_ISO_FRAMES) -DOPENA8DJ_CAPTURE_QUEUE_DEPTH=$(HAL_CAPTURE_QUEUE) -DOPENA8DJ_PLAYBACK_QUEUE_TARGET=$(HAL_PLAYBACK_QUEUE) -DOPENA8DJ_PLAYBACK_CAPTURE_PACED=$(HAL_PLAYBACK_CAPTURE_PACED) -DOPENA8DJ_CAPTURE_PACED_OUT_LEAD=$(HAL_CAPTURE_PACED_OUT_LEAD) -DOPENA8DJ_CAPTURE_PACED_PLAYBACK_REFILL=$(HAL_CAPTURE_PACED_PLAYBACK_REFILL) -DOPENA8DJ_PLAYBACK_COALESCE_TRANSFERS=$(HAL_PLAYBACK_COALESCE_TRANSFERS) -DOPENA8DJ_HAL_PREPARED_USB_SUBMIT_RUNTIME=$(HAL_PREPARED_USB_SUBMIT_RUNTIME) -DOPENA8DJ_HAL_PREPARED_USB_PLAYBACK_ONLY_RUNTIME=$(HAL_PREPARED_USB_PLAYBACK_ONLY_RUNTIME) -DOPENA8DJ_HAL_PREPARED_USB_SLOTS_PER_SUBMIT=$(HAL_PREPARED_USB_SLOTS_PER_SUBMIT) -DOPENA8DJ_QUEUE_PLAYBACK_BEFORE_CAPTURE_REQUEUE=$(HAL_QUEUE_PLAYBACK_BEFORE_CAPTURE_REQUEUE) -DOPENA8DJ_ENABLE_USB_CLOCK_ANCHOR=$(HAL_USB_CLOCK_ANCHOR) -DOPENA8DJ_ENABLE_USB_STABLE_FRAME_POLL=$(HAL_USB_STABLE_FRAME) -DOPENA8DJ_ENABLE_USB_ZERO_TIMESTAMP=$(HAL_USB_ZERO_TIMESTAMP) -DOPENA8DJ_USB_ANCHOR_FILTER=$(HAL_USB_ANCHOR_FILTER) -DOPENA8DJ_ENABLE_EXPLICIT_ISOC_SCHEDULING=$(HAL_EXPLICIT_SCHED) -DOPENA8DJ_EXPLICIT_SCHED_FALLBACK_ON_QUEUE_FAILURE=$(HAL_EXPLICIT_SCHED_FAIL_FALLBACK) -DOPENA8DJ_ENABLE_ELASTIC_OUTPUT=$(HAL_ELASTIC_OUTPUT) -DOPENA8DJ_OUTPUT_NATIVE_I24=$(HAL_OUTPUT_NATIVE) -DOPENA8DJ_FAST_OUTPUT_QUANTIZER=$(HAL_FAST_OUTPUT_QUANTIZER) -DOPENA8DJ_FAST_OUTPUT_PREFETCH_CLEAR=$(HAL_FAST_OUTPUT_PREFETCH_CLEAR) -DOPENA8DJ_ENABLE_UNROLLED_OUTPUT_PACK=$(HAL_UNROLLED_OUTPUT_PACK) -DOPENA8DJ_ENABLE_STREAM_USAGE_PROPERTY=$(HAL_STREAM_USAGE) -DOPENA8DJ_ENABLE_TRANSFER_POOL=$(HAL_TRANSFER_POOL) -DOPENA8DJ_STRICT_TRANSFER_POOL=$(HAL_STRICT_TRANSFER_POOL) -DOPENA8DJ_TRANSFER_POOL_CURSOR=$(HAL_TRANSFER_POOL_CURSOR) -DOPENA8DJ_REUSE_ISOC_COMPLETIONS=$(HAL_REUSE_ISOC_COMPLETIONS) -DOPENA8DJ_RAW_ISOC_COMPLETIONS=$(HAL_RAW_ISOC_COMPLETIONS) -DOPENA8DJ_ENABLE_LEGACY_OUT_SLOTS=$(HAL_LEGACY_OUT_SLOTS) -DOPENA8DJ_USB_QUEUE_QOS=$(HAL_USB_QUEUE_QOS) -DOPENA8DJ_FAST_ISO_TRANSFER_CONFIG=$(HAL_FAST_ISO_TRANSFER_CONFIG) -DOPENA8DJ_ENABLE_TRANSFER_LEDGER=$(HAL_TRANSFER_LEDGER) -DOPENA8DJ_ENABLE_PLAYBACK_PAYLOAD_GUARD=$(HAL_PLAYBACK_PAYLOAD_GUARD) -DOPENA8DJ_PROPERTY_BACKOFF_USEC=$(HAL_PROPERTY_BACKOFF_USEC) -DOPENA8DJ_OUTPUT_START_BYTE=$(HAL_OUTPUT_START_BYTE) -DOPENA8DJ_OUTPUT_CHECK_OFFSET=$(HAL_OUTPUT_CHECK_OFFSET) -DOPENA8DJ_ENABLE_OUTPUT_SAMPLE_TIME_FOLLOWER=$(HAL_OUTPUT_SAMPLE_TIME_FOLLOWER) -DOPENA8DJ_IGNORE_OUTPUT_SAMPLE_TIME=$(HAL_IGNORE_OUTPUT_SAMPLE_TIME) -DOPENA8DJ_FLUSH_OUTPUT_IN_WRITE_MIX=$(HAL_FLUSH_OUTPUT_IN_WRITE_MIX) -DOPENA8DJ_FLUSH_TOUCHED_OUTPUT=$(HAL_FLUSH_TOUCHED_OUTPUT) -DOPENA8DJ_ENABLE_CADENCE_DIAGNOSTIC=$(HAL_CADENCE_DIAGNOSTIC) -DOPENA8DJ_ENABLE_STREAM_KEEPALIVE=$(HAL_STREAM_KEEPALIVE) -DOPENA8DJ_STRICT_IDLE_SILENCE=$(HAL_STRICT_IDLE_SILENCE) -DOPENA8DJ_IDLE_PLAYBACK_GATE=$(HAL_IDLE_PLAYBACK_GATE) -DOPENA8DJ_IDLE_PLAYBACK_GATE_THRESHOLD=$(HAL_IDLE_PLAYBACK_GATE_THRESHOLD) -DOPENA8DJ_IDLE_PLAYBACK_GATE_HOLD_FRAMES=$(HAL_IDLE_PLAYBACK_GATE_HOLD_FRAMES) -DOPENA8DJ_OUTPUT_ZERO_FLOOR=$(HAL_OUTPUT_ZERO_FLOOR) -DOPENA8DJ_OUTPUT_START_LATENCY_FRAMES=$(HAL_OUTPUT_START_LATENCY_FRAMES) -DOPENA8DJ_OUTPUT_RESTART_LATENCY_FRAMES=$(HAL_OUTPUT_RESTART_LATENCY_FRAMES) -DOPENA8DJ_OUTPUT_TARGET_LATENCY_FRAMES=$(HAL_OUTPUT_TARGET_LATENCY_FRAMES) -DOPENA8DJ_OUTPUT_ELASTIC_HIGH_WATER_FRAMES=$(HAL_OUTPUT_ELASTIC_HIGH_WATER_FRAMES) -DOPENA8DJ_ENABLE_OUTPUT_AMPLITUDE_STATS=$(HAL_OUTPUT_AMPLITUDE_STATS) -DOPENA8DJ_ENABLE_OUTPUT_WRITE_STATS=$(HAL_OUTPUT_WRITE_STATS) -DOPENA8DJ_ENABLE_HOT_STREAM_STATS=$(HAL_HOT_STREAM_STATS) -DOPENA8DJ_ENABLE_HOT_PATH_TIMING=$(HAL_HOT_PATH_TIMING) -DOPENA8DJ_ENABLE_TRACE=$(HAL_TRACE) -DOPENA8DJ_HOT_STREAM_STATS_INTERVAL=$(HAL_HOT_STREAM_STATS_INTERVAL) -DOPENA8DJ_ENABLE_STREAM_STATS_ATOMIC_ACCUMULATORS=$(HAL_STREAM_STATS_ATOMIC_ACCUMULATORS) -DOPENA8DJ_VALID_CAPTURE_OUT_LAYOUT=$(HAL_VALID_CAPTURE_OUT_LAYOUT) -DOPENA8DJ_SELECT_ALT0_BEFORE_ALT1=$(HAL_SELECT_ALT0_BEFORE_ALT1) -DOPENA8DJ_BACKGROUND_WARM_OPEN=$(HAL_BACKGROUND_WARM_OPEN) -DOPENA8DJ_BACKGROUND_PREOPEN_ON_INIT=$(HAL_BACKGROUND_PREOPEN_ON_INIT) -DOPENA8DJ_INVERT_OUTPUT_RIGHT_CHANNELS=$(HAL_INVERT_OUTPUT_RIGHT) -DOPENA8DJ_STOP_GRACE_USEC=$(HAL_STOP_GRACE_USEC) -DOPENA8DJ_STOP_ISOC_ON_STOP=$(HAL_STOP_ISOC_ON_STOP) -DOPENA8DJ_RESET_AUDIO_PARAMS_BEFORE_STREAM=$(HAL_RESET_AUDIO_PARAMS_BEFORE_STREAM) -DOPENA8DJ_AUDIO_PARAMS_RESET_WAIT_FOR_REPLY=$(HAL_AUDIO_PARAMS_RESET_WAIT_FOR_REPLY) -DOPENA8DJ_AUDIO_PARAMS_RESET_SETTLE_USEC=$(HAL_AUDIO_PARAMS_RESET_SETTLE_USEC)
HAL_CFLAGS += -DOPENA8DJ_REUSE_ISOC_COMPLETION_HANDLERS=$(HAL_REUSE_ISOC_COMPLETIONS)
HAL_CFLAGS += -DOPENA8DJ_RAW_ISOC_COMPLETION_HANDLERS=$(HAL_RAW_ISOC_COMPLETIONS)
HAL_CFLAGS += -DOPENA8DJ_CLOCK_DRIFT_TOLERANCE=$(HAL_CLOCK_DRIFT_TOLERANCE)
HAL_CFLAGS += -DOPENA8DJ_ENABLE_OUTPUT_FIFO=$(HAL_OUTPUT_FIFO)
HAL_CFLAGS += -DOPENA8DJ_TIMECODE_INPUT_GAIN=$(HAL_TIMECODE_INPUT_GAIN)
HAL_CFLAGS += -DOPENA8DJ_TIMECODE_INPUT_GATE_THRESHOLD=$(HAL_TIMECODE_INPUT_GATE_THRESHOLD)
HAL_CFLAGS += -DOPENA8DJ_TIMECODE_INPUT_GATE_HOLD_FRAMES=$(HAL_TIMECODE_INPUT_GATE_HOLD_FRAMES)
HAL_CFLAGS += -DOPENA8DJ_DIAGNOSTIC_DIR_DEFAULT=\"$(HAL_DIAGNOSTIC_DIR_DEFAULT)\"
ifeq ($(HAL_PREPARED_USB_SUBMIT_RUNTIME),1)
HAL_SRC := $(HAL_BASE_SRC) $(HAL_PREPARED_RUNTIME_SRC)
HAL_LD := xcrun clang++
HAL_CFLAGS += -Icore/include -Isrc/hal
HAL_CPP_CFLAGS := $(filter-out -fobjc-arc,$(HAL_CFLAGS)) -std=c++20
endif
FRAMEWORKS := -framework Foundation -framework IOKit -framework IOUSBHost
HAL_FRAMEWORKS := -framework CoreAudio -framework CoreFoundation -framework AudioToolbox -framework CoreMIDI -framework Foundation -framework IOKit -framework IOUSBHost
MIDI_FRAMEWORKS := -framework Foundation -framework CoreMIDI -framework CoreAudio -framework CoreFoundation

.PHONY: all clean probe claim hal hal-usb-clock-candidate hal-human-test-lite-candidate hal-traktor-recovery-candidate hal-prepared-runtime hal-prepared-runtime-candidate hal-playback-scheduler-candidate hal-prepared-lite-candidate hal-prepared-medium-candidate hal-cpu-pool-candidate hal-cadence-diagnostic hal-hotpath-diagnostic hal-hotpath-diagnostic-candidate hal-capture-batch-diagnostic hal-capture-batch-v2-diagnostic hal-timecode-frozen-good-candidate hal-timecode-frozen-good-output4096-candidate hal-timecode-frozen-good-output3072-candidate hal-timecode-frozen-good-output3008-candidate hal-timecode-frozen-good-prefetch64-candidate hal-timecode-frozen-good-restart1024-candidate hal-timecode-frozen-good-start2816-candidate hal-timecode-frozen-good-output2560-candidate hal-timecode-frozen-good-output2816-candidate hal-timecode-frozen-good-output2304-candidate hal-timecode-frozen-good-output2048-candidate hal-timecode-frozen-good-responsive-candidate hal-timecode-responsive-candidate hal-timecode-low-noise-candidate freeze-timecode-responsive2816-candidate freeze-timecode-stable3072-candidate timecode-latency-e2e-fixture timecode-latency-offline-gate sign-hal sign-tools install-hal install-midid install-tools install-control-surfaces control-center smoke-hal parity-smoke-hal audio-list audio-inspect audio-io-test audio-wav-play audio-record audio-config audio-default audio-pair-tone audio-route audio-input-meter macbook-mic-record audio-stack-health audio-stack-guard audio-stack-recover audio-stack-reset soundcheck-preflight soundcheck soundcheck-irig-calibrated direct-usb-soundcheck simulated-output-soundcheck usb-play usb-play-plain usb-play-plain-gain05 usb-input-meter midi-list physical-run-compare package control-surfaces-package tools-package dmg control-surfaces-dmg tools-dmg driver-checksums driver-dist checksums dist release-signed notarize verify-signed-release FORCE

all: $(TOOL) hal $(AUDIO_LIST) $(AUDIO_INSPECT) $(AUDIO_IO_TEST) $(AUDIO_WAV_PLAY) $(AUDIO_RECORD) $(AUDIO_CONFIG) $(AUDIO_DEFAULT) $(AUDIO_PAIR_TONE) $(AUDIO_ROUTE) $(INPUT_METER) $(MACBOOK_MIC_RECORD) $(USB_PLAY) $(USB_INPUT_METER) $(MIDI_BRIDGE) $(CONTROL_TOOL) $(MIDI_LIST)

$(TOOL): $(SRC)
	@mkdir -p build
	$(CC) $(CFLAGS) $(FRAMEWORKS) -o $@ $<

hal: $(HAL_BIN) $(CONTROL_TOOL)

hal-usb-clock-candidate:
	python3 scripts/build-hal-usb-clock-candidate \
		--candidate build/OpenA8DJ-usb-clock.driver \
		--json-out build/hal-candidates/usb-clock-candidate.json

hal-human-test-lite-candidate:
	python3 scripts/build-hal-human-test-lite-candidate \
		--candidate build/OpenA8DJ-human-test-lite.driver \
		--json-out build/hal-candidates/human-test-lite-candidate.json

hal-traktor-recovery-candidate:
	python3 scripts/build-hal-traktor-recovery-candidate \
		--candidate build/OpenA8DJ-traktor-recovery.driver \
		--json-out build/hal-candidates/traktor-recovery-candidate.json

hal-prepared-runtime:
	$(MAKE) -B hal \
		HAL_PREPARED_USB_SUBMIT_RUNTIME=1 \
		HAL_PREPARED_USB_SLOTS_PER_SUBMIT=8 \
		HAL_ISO_FRAMES=8 \
		HAL_CAPTURE_ISO_FRAMES=64 \
		HAL_PLAYBACK_ISO_FRAMES=8 \
		HAL_PLAYBACK_COALESCE_TRANSFERS=8 \
		HAL_CAPTURE_QUEUE=8 \
		HAL_PLAYBACK_QUEUE=8

hal-prepared-runtime-candidate:
	python3 scripts/build-hal-prepared-runtime-candidate \
		--candidate build/OpenA8DJ-prepared-runtime.driver \
		--json-out build/hal-candidates/prepared-runtime-candidate.json

hal-playback-scheduler-candidate:
	python3 scripts/build-hal-prepared-runtime-candidate \
		--candidate build/OpenA8DJ-playback-scheduler.driver \
		--json-out build/hal-candidates/playback-scheduler-candidate.json \
		--playback-only

hal-prepared-lite-candidate:
	python3 scripts/build-hal-prepared-runtime-candidate \
		--candidate build/OpenA8DJ-prepared-lite.driver \
		--json-out build/hal-candidates/prepared-lite-candidate.json \
		--slots-per-submit 2 \
		--capture-queue 4 \
		--playback-queue 4

hal-prepared-medium-candidate:
	python3 scripts/build-hal-prepared-runtime-candidate \
		--candidate build/OpenA8DJ-prepared-medium.driver \
		--json-out build/hal-candidates/prepared-medium-candidate.json \
		--slots-per-submit 4 \
		--logical-iso-frames 8 \
		--playback-base-iso-frames 8 \
		--capture-queue 8 \
		--playback-queue 8

hal-cpu-pool-candidate:
	python3 scripts/build-hal-cpu-pool-candidate \
		--candidate build/OpenA8DJ-cpu-pool.driver \
		--json-out build/hal-candidates/cpu-pool-candidate.json

hal-cadence-diagnostic:
	$(MAKE) -B hal \
		HAL_CADENCE_DIAGNOSTIC=1 \
		HAL_TRANSFER_LEDGER=1 \
		HAL_PLAYBACK_PAYLOAD_GUARD=1 \
		HAL_OUTPUT_AMPLITUDE_STATS=1 \
		HAL_HOT_STREAM_STATS_INTERVAL=1 \
		HAL_STREAM_STATS_ATOMIC_ACCUMULATORS=1

hal-hotpath-diagnostic:
	$(MAKE) -B hal \
		HAL_HOT_PATH_TIMING=1 \
		HAL_HOT_STREAM_STATS_INTERVAL=1 \
		HAL_STREAM_STATS_ATOMIC_ACCUMULATORS=1 \
		HAL_TRANSFER_LEDGER=0 \
		HAL_PLAYBACK_PAYLOAD_GUARD=0 \
		HAL_CADENCE_DIAGNOSTIC=0

hal-hotpath-diagnostic-candidate:
	python3 scripts/build-hal-hotpath-diagnostic-candidate \
		--candidate build/OpenA8DJ-hotpath-diagnostic.driver \
		--json-out build/hal-candidates/hotpath-diagnostic-candidate.json

hal-capture-batch-diagnostic:
	$(MAKE) -B hal \
		HAL_ISO_FRAMES=8 \
		HAL_CAPTURE_ISO_FRAMES=64 \
		HAL_PLAYBACK_ISO_FRAMES=8 \
		HAL_PLAYBACK_COALESCE_TRANSFERS=1 \
		HAL_CAPTURE_QUEUE=8 \
		HAL_PLAYBACK_QUEUE=8 \
		HAL_PLAYBACK_CAPTURE_PACED=1 \
		HAL_PREPARED_USB_SUBMIT_RUNTIME=0 \
		HAL_CADENCE_DIAGNOSTIC=1 \
		HAL_HOT_STREAM_STATS_INTERVAL=1 \
		HAL_STREAM_STATS_ATOMIC_ACCUMULATORS=1

hal-capture-batch-v2-diagnostic:
	$(MAKE) -B hal \
		HAL_ISO_FRAMES=8 \
		HAL_CAPTURE_ISO_FRAMES=16 \
		HAL_PLAYBACK_ISO_FRAMES=8 \
		HAL_PLAYBACK_COALESCE_TRANSFERS=1 \
		HAL_CAPTURE_QUEUE=8 \
		HAL_PLAYBACK_QUEUE=8 \
		HAL_PLAYBACK_CAPTURE_PACED=1 \
		HAL_PREPARED_USB_SUBMIT_RUNTIME=0 \
		HAL_OUTPUT_STREAMS=1 \
		HAL_STREAM_USAGE=0 \
		HAL_CADENCE_DIAGNOSTIC=1 \
		HAL_HOT_STREAM_STATS_INTERVAL=1 \
		HAL_STREAM_STATS_ATOMIC_ACCUMULATORS=1

hal-input-spsc-diagnostic:
	$(MAKE) -B hal \
		HAL_INPUT_SPSC_RING=1 \
		HAL_ISO_FRAMES=8 \
		HAL_CAPTURE_ISO_FRAMES=8 \
		HAL_PLAYBACK_ISO_FRAMES=8 \
		HAL_PLAYBACK_COALESCE_TRANSFERS=1 \
		HAL_CAPTURE_QUEUE=8 \
		HAL_PLAYBACK_QUEUE=8 \
		HAL_OUTPUT_STREAMS=1 \
		HAL_STREAM_USAGE=0

hal-timecode-frozen-good-candidate:
	$(MAKE) -B hal \
		HAL_TIMECODE_INPUT_GAIN=1.0f \
		HAL_TIMECODE_INPUT_GATE_THRESHOLD=0.0f \
		HAL_TIMECODE_INPUT_GATE_HOLD_FRAMES=0 \
		HAL_INPUT_MAX_LATENCY_FRAMES=0 \
		HAL_OUTPUT_GAIN=$(HAL_OUTPUT_GAIN) \
		HAL_IDLE_PLAYBACK_GATE_THRESHOLD=0.000001f \
		HAL_IDLE_PLAYBACK_GATE_HOLD_FRAMES=0 \
		HAL_OUTPUT_ZERO_FLOOR=0.0f \
		HAL_BACKGROUND_PREOPEN_ON_INIT=$(HAL_BACKGROUND_PREOPEN_ON_INIT) \
		HAL_STOP_ISOC_ON_STOP=$(HAL_STOP_ISOC_ON_STOP) \
		HAL_RESET_AUDIO_PARAMS_BEFORE_STREAM=$(HAL_RESET_AUDIO_PARAMS_BEFORE_STREAM) \
		HAL_AUDIO_PARAMS_RESET_WAIT_FOR_REPLY=$(HAL_AUDIO_PARAMS_RESET_WAIT_FOR_REPLY)

hal-timecode-frozen-good-output4096-candidate:
	$(MAKE) -B hal \
		HAL_TIMECODE_INPUT_GAIN=1.0f \
		HAL_TIMECODE_INPUT_GATE_THRESHOLD=0.0f \
		HAL_TIMECODE_INPUT_GATE_HOLD_FRAMES=0 \
		HAL_INPUT_MAX_LATENCY_FRAMES=0 \
		HAL_OUTPUT_GAIN=$(HAL_OUTPUT_GAIN) \
		HAL_IDLE_PLAYBACK_GATE_THRESHOLD=0.000001f \
		HAL_IDLE_PLAYBACK_GATE_HOLD_FRAMES=0 \
		HAL_OUTPUT_ZERO_FLOOR=0.0f \
		HAL_OUTPUT_START_LATENCY_FRAMES=4096 \
		HAL_OUTPUT_RESTART_LATENCY_FRAMES=2048 \
		HAL_OUTPUT_TARGET_LATENCY_FRAMES=4096 \
		HAL_OUTPUT_ELASTIC_HIGH_WATER_FRAMES=12288 \
		HAL_BACKGROUND_PREOPEN_ON_INIT=$(HAL_BACKGROUND_PREOPEN_ON_INIT) \
		HAL_STOP_ISOC_ON_STOP=$(HAL_STOP_ISOC_ON_STOP) \
		HAL_RESET_AUDIO_PARAMS_BEFORE_STREAM=$(HAL_RESET_AUDIO_PARAMS_BEFORE_STREAM) \
		HAL_AUDIO_PARAMS_RESET_WAIT_FOR_REPLY=$(HAL_AUDIO_PARAMS_RESET_WAIT_FOR_REPLY)

hal-timecode-frozen-good-output3072-candidate:
	$(MAKE) -B hal \
		HAL_TIMECODE_INPUT_GAIN=1.0f \
		HAL_TIMECODE_INPUT_GATE_THRESHOLD=0.0f \
		HAL_TIMECODE_INPUT_GATE_HOLD_FRAMES=0 \
		HAL_INPUT_MAX_LATENCY_FRAMES=0 \
		HAL_OUTPUT_GAIN=$(HAL_OUTPUT_GAIN) \
		HAL_IDLE_PLAYBACK_GATE_THRESHOLD=0.000001f \
		HAL_IDLE_PLAYBACK_GATE_HOLD_FRAMES=0 \
		HAL_OUTPUT_ZERO_FLOOR=0.0f \
		HAL_OUTPUT_START_LATENCY_FRAMES=3072 \
		HAL_OUTPUT_RESTART_LATENCY_FRAMES=1536 \
		HAL_OUTPUT_TARGET_LATENCY_FRAMES=3072 \
		HAL_OUTPUT_ELASTIC_HIGH_WATER_FRAMES=9216 \
		HAL_BACKGROUND_PREOPEN_ON_INIT=$(HAL_BACKGROUND_PREOPEN_ON_INIT) \
		HAL_STOP_ISOC_ON_STOP=$(HAL_STOP_ISOC_ON_STOP) \
		HAL_RESET_AUDIO_PARAMS_BEFORE_STREAM=$(HAL_RESET_AUDIO_PARAMS_BEFORE_STREAM) \
		HAL_AUDIO_PARAMS_RESET_WAIT_FOR_REPLY=$(HAL_AUDIO_PARAMS_RESET_WAIT_FOR_REPLY)

hal-timecode-frozen-good-output3008-candidate:
	$(MAKE) -B hal \
		HAL_TIMECODE_INPUT_GAIN=1.0f \
		HAL_TIMECODE_INPUT_GATE_THRESHOLD=0.0f \
		HAL_TIMECODE_INPUT_GATE_HOLD_FRAMES=0 \
		HAL_INPUT_MAX_LATENCY_FRAMES=0 \
		HAL_OUTPUT_GAIN=$(HAL_OUTPUT_GAIN) \
		HAL_IDLE_PLAYBACK_GATE_THRESHOLD=0.000001f \
		HAL_IDLE_PLAYBACK_GATE_HOLD_FRAMES=0 \
		HAL_OUTPUT_ZERO_FLOOR=0.0f \
		HAL_OUTPUT_START_LATENCY_FRAMES=3008 \
		HAL_OUTPUT_RESTART_LATENCY_FRAMES=1504 \
		HAL_OUTPUT_TARGET_LATENCY_FRAMES=3008 \
		HAL_OUTPUT_ELASTIC_HIGH_WATER_FRAMES=9024 \
		HAL_BACKGROUND_PREOPEN_ON_INIT=$(HAL_BACKGROUND_PREOPEN_ON_INIT) \
		HAL_STOP_ISOC_ON_STOP=$(HAL_STOP_ISOC_ON_STOP) \
		HAL_RESET_AUDIO_PARAMS_BEFORE_STREAM=$(HAL_RESET_AUDIO_PARAMS_BEFORE_STREAM) \
		HAL_AUDIO_PARAMS_RESET_WAIT_FOR_REPLY=$(HAL_AUDIO_PARAMS_RESET_WAIT_FOR_REPLY)

hal-timecode-frozen-good-prefetch64-candidate:
	$(MAKE) -B hal \
		HAL_TIMECODE_INPUT_GAIN=1.0f \
		HAL_TIMECODE_INPUT_GATE_THRESHOLD=0.0f \
		HAL_TIMECODE_INPUT_GATE_HOLD_FRAMES=0 \
		HAL_INPUT_MAX_LATENCY_FRAMES=0 \
		HAL_OUTPUT_GAIN=$(HAL_OUTPUT_GAIN) \
		HAL_OUTPUT_PREFETCH_FRAMES=64 \
		HAL_IDLE_PLAYBACK_GATE_THRESHOLD=0.000001f \
		HAL_IDLE_PLAYBACK_GATE_HOLD_FRAMES=0 \
		HAL_OUTPUT_ZERO_FLOOR=0.0f \
		HAL_OUTPUT_START_LATENCY_FRAMES=3072 \
		HAL_OUTPUT_RESTART_LATENCY_FRAMES=1536 \
		HAL_OUTPUT_TARGET_LATENCY_FRAMES=3072 \
		HAL_OUTPUT_ELASTIC_HIGH_WATER_FRAMES=9216 \
		HAL_BACKGROUND_PREOPEN_ON_INIT=$(HAL_BACKGROUND_PREOPEN_ON_INIT) \
		HAL_STOP_ISOC_ON_STOP=$(HAL_STOP_ISOC_ON_STOP) \
		HAL_RESET_AUDIO_PARAMS_BEFORE_STREAM=$(HAL_RESET_AUDIO_PARAMS_BEFORE_STREAM) \
		HAL_AUDIO_PARAMS_RESET_WAIT_FOR_REPLY=$(HAL_AUDIO_PARAMS_RESET_WAIT_FOR_REPLY)

hal-timecode-frozen-good-restart1024-candidate:
	$(MAKE) -B hal \
		HAL_TIMECODE_INPUT_GAIN=1.0f \
		HAL_TIMECODE_INPUT_GATE_THRESHOLD=0.0f \
		HAL_TIMECODE_INPUT_GATE_HOLD_FRAMES=0 \
		HAL_INPUT_MAX_LATENCY_FRAMES=0 \
		HAL_OUTPUT_GAIN=$(HAL_OUTPUT_GAIN) \
		HAL_IDLE_PLAYBACK_GATE_THRESHOLD=0.000001f \
		HAL_IDLE_PLAYBACK_GATE_HOLD_FRAMES=0 \
		HAL_OUTPUT_ZERO_FLOOR=0.0f \
		HAL_OUTPUT_START_LATENCY_FRAMES=3072 \
		HAL_OUTPUT_RESTART_LATENCY_FRAMES=1024 \
		HAL_OUTPUT_TARGET_LATENCY_FRAMES=3072 \
		HAL_OUTPUT_ELASTIC_HIGH_WATER_FRAMES=9216 \
		HAL_BACKGROUND_PREOPEN_ON_INIT=$(HAL_BACKGROUND_PREOPEN_ON_INIT) \
		HAL_STOP_ISOC_ON_STOP=$(HAL_STOP_ISOC_ON_STOP) \
		HAL_RESET_AUDIO_PARAMS_BEFORE_STREAM=$(HAL_RESET_AUDIO_PARAMS_BEFORE_STREAM) \
		HAL_AUDIO_PARAMS_RESET_WAIT_FOR_REPLY=$(HAL_AUDIO_PARAMS_RESET_WAIT_FOR_REPLY)

hal-timecode-frozen-good-start2816-candidate:
	$(MAKE) -B hal \
		HAL_TIMECODE_INPUT_GAIN=1.0f \
		HAL_TIMECODE_INPUT_GATE_THRESHOLD=0.0f \
		HAL_TIMECODE_INPUT_GATE_HOLD_FRAMES=0 \
		HAL_INPUT_MAX_LATENCY_FRAMES=0 \
		HAL_OUTPUT_GAIN=$(HAL_OUTPUT_GAIN) \
		HAL_IDLE_PLAYBACK_GATE_THRESHOLD=0.000001f \
		HAL_IDLE_PLAYBACK_GATE_HOLD_FRAMES=0 \
		HAL_OUTPUT_ZERO_FLOOR=0.0f \
		HAL_OUTPUT_START_LATENCY_FRAMES=2816 \
		HAL_OUTPUT_RESTART_LATENCY_FRAMES=1536 \
		HAL_OUTPUT_TARGET_LATENCY_FRAMES=3072 \
		HAL_OUTPUT_ELASTIC_HIGH_WATER_FRAMES=9216 \
		HAL_BACKGROUND_PREOPEN_ON_INIT=$(HAL_BACKGROUND_PREOPEN_ON_INIT) \
		HAL_STOP_ISOC_ON_STOP=$(HAL_STOP_ISOC_ON_STOP) \
		HAL_RESET_AUDIO_PARAMS_BEFORE_STREAM=$(HAL_RESET_AUDIO_PARAMS_BEFORE_STREAM) \
		HAL_AUDIO_PARAMS_RESET_WAIT_FOR_REPLY=$(HAL_AUDIO_PARAMS_RESET_WAIT_FOR_REPLY)

hal-timecode-frozen-good-output2560-candidate:
	$(MAKE) -B hal \
		HAL_TIMECODE_INPUT_GAIN=1.0f \
		HAL_TIMECODE_INPUT_GATE_THRESHOLD=0.0f \
		HAL_TIMECODE_INPUT_GATE_HOLD_FRAMES=0 \
		HAL_INPUT_MAX_LATENCY_FRAMES=0 \
		HAL_OUTPUT_GAIN=$(HAL_OUTPUT_GAIN) \
		HAL_IDLE_PLAYBACK_GATE_THRESHOLD=0.000001f \
		HAL_IDLE_PLAYBACK_GATE_HOLD_FRAMES=0 \
		HAL_OUTPUT_ZERO_FLOOR=0.0f \
		HAL_OUTPUT_START_LATENCY_FRAMES=2560 \
		HAL_OUTPUT_RESTART_LATENCY_FRAMES=1280 \
		HAL_OUTPUT_TARGET_LATENCY_FRAMES=2560 \
		HAL_OUTPUT_ELASTIC_HIGH_WATER_FRAMES=7680 \
		HAL_BACKGROUND_PREOPEN_ON_INIT=$(HAL_BACKGROUND_PREOPEN_ON_INIT) \
		HAL_STOP_ISOC_ON_STOP=$(HAL_STOP_ISOC_ON_STOP) \
		HAL_RESET_AUDIO_PARAMS_BEFORE_STREAM=$(HAL_RESET_AUDIO_PARAMS_BEFORE_STREAM) \
		HAL_AUDIO_PARAMS_RESET_WAIT_FOR_REPLY=$(HAL_AUDIO_PARAMS_RESET_WAIT_FOR_REPLY)

hal-timecode-frozen-good-output2816-candidate:
	$(MAKE) -B hal \
		HAL_TIMECODE_INPUT_GAIN=1.0f \
		HAL_TIMECODE_INPUT_GATE_THRESHOLD=0.0f \
		HAL_TIMECODE_INPUT_GATE_HOLD_FRAMES=0 \
		HAL_INPUT_MAX_LATENCY_FRAMES=0 \
		HAL_OUTPUT_GAIN=$(HAL_OUTPUT_GAIN) \
		HAL_IDLE_PLAYBACK_GATE_THRESHOLD=0.000001f \
		HAL_IDLE_PLAYBACK_GATE_HOLD_FRAMES=0 \
		HAL_OUTPUT_ZERO_FLOOR=0.0f \
		HAL_OUTPUT_START_LATENCY_FRAMES=2816 \
		HAL_OUTPUT_RESTART_LATENCY_FRAMES=1408 \
		HAL_OUTPUT_TARGET_LATENCY_FRAMES=2816 \
		HAL_OUTPUT_ELASTIC_HIGH_WATER_FRAMES=8448 \
		HAL_BACKGROUND_PREOPEN_ON_INIT=$(HAL_BACKGROUND_PREOPEN_ON_INIT) \
		HAL_STOP_ISOC_ON_STOP=$(HAL_STOP_ISOC_ON_STOP) \
		HAL_RESET_AUDIO_PARAMS_BEFORE_STREAM=$(HAL_RESET_AUDIO_PARAMS_BEFORE_STREAM) \
		HAL_AUDIO_PARAMS_RESET_WAIT_FOR_REPLY=$(HAL_AUDIO_PARAMS_RESET_WAIT_FOR_REPLY)

freeze-timecode-responsive2816-candidate:
	python3 scripts/freeze-timecode-candidate \
		--build-target hal-timecode-frozen-good-output2816-candidate \
		--candidate build/OpenA8DJ-frozen-responsive2816.driver \
		--json-out build/hal-candidates/frozen-responsive2816.json \
		--profile-name output2816 \
		--output-target-frames 2816 \
		--output-start-latency-frames 2816 \
		--output-restart-latency-frames 1408 \
		--output-elastic-high-water-frames 8448

freeze-timecode-stable3072-candidate:
	python3 scripts/freeze-timecode-candidate \
		--build-target hal-timecode-frozen-good-output3072-candidate \
		--candidate build/OpenA8DJ-frozen-stable3072.driver \
		--json-out build/hal-candidates/frozen-stable3072.json \
		--profile-name output3072 \
		--output-target-frames 3072 \
		--output-start-latency-frames 3072 \
		--output-restart-latency-frames 1536 \
		--output-elastic-high-water-frames 9216 \
		--selection-reason "Frozen safe profile after output2816 failed fresh recovery; preserves responsive 3072 geometry as the current usable version." \
		--physical-quality-status "NOT_CERTIFIED"

hal-timecode-frozen-good-output2304-candidate:
	$(MAKE) -B hal \
		HAL_TIMECODE_INPUT_GAIN=1.0f \
		HAL_TIMECODE_INPUT_GATE_THRESHOLD=0.0f \
		HAL_TIMECODE_INPUT_GATE_HOLD_FRAMES=0 \
		HAL_INPUT_MAX_LATENCY_FRAMES=0 \
		HAL_OUTPUT_GAIN=$(HAL_OUTPUT_GAIN) \
		HAL_IDLE_PLAYBACK_GATE_THRESHOLD=0.000001f \
		HAL_IDLE_PLAYBACK_GATE_HOLD_FRAMES=0 \
		HAL_OUTPUT_ZERO_FLOOR=0.0f \
		HAL_OUTPUT_START_LATENCY_FRAMES=2304 \
		HAL_OUTPUT_RESTART_LATENCY_FRAMES=1152 \
		HAL_OUTPUT_TARGET_LATENCY_FRAMES=2304 \
		HAL_OUTPUT_ELASTIC_HIGH_WATER_FRAMES=6912 \
		HAL_BACKGROUND_PREOPEN_ON_INIT=$(HAL_BACKGROUND_PREOPEN_ON_INIT) \
		HAL_STOP_ISOC_ON_STOP=$(HAL_STOP_ISOC_ON_STOP) \
		HAL_RESET_AUDIO_PARAMS_BEFORE_STREAM=$(HAL_RESET_AUDIO_PARAMS_BEFORE_STREAM) \
		HAL_AUDIO_PARAMS_RESET_WAIT_FOR_REPLY=$(HAL_AUDIO_PARAMS_RESET_WAIT_FOR_REPLY)

hal-timecode-frozen-good-output2048-candidate:
	$(MAKE) -B hal \
		HAL_TIMECODE_INPUT_GAIN=1.0f \
		HAL_TIMECODE_INPUT_GATE_THRESHOLD=0.0f \
		HAL_TIMECODE_INPUT_GATE_HOLD_FRAMES=0 \
		HAL_INPUT_MAX_LATENCY_FRAMES=0 \
		HAL_OUTPUT_GAIN=$(HAL_OUTPUT_GAIN) \
		HAL_IDLE_PLAYBACK_GATE_THRESHOLD=0.000001f \
		HAL_IDLE_PLAYBACK_GATE_HOLD_FRAMES=0 \
		HAL_OUTPUT_ZERO_FLOOR=0.0f \
		HAL_OUTPUT_START_LATENCY_FRAMES=2048 \
		HAL_OUTPUT_RESTART_LATENCY_FRAMES=1024 \
		HAL_OUTPUT_TARGET_LATENCY_FRAMES=2048 \
		HAL_OUTPUT_ELASTIC_HIGH_WATER_FRAMES=6144 \
		HAL_BACKGROUND_PREOPEN_ON_INIT=$(HAL_BACKGROUND_PREOPEN_ON_INIT) \
		HAL_STOP_ISOC_ON_STOP=$(HAL_STOP_ISOC_ON_STOP) \
		HAL_RESET_AUDIO_PARAMS_BEFORE_STREAM=$(HAL_RESET_AUDIO_PARAMS_BEFORE_STREAM) \
		HAL_AUDIO_PARAMS_RESET_WAIT_FOR_REPLY=$(HAL_AUDIO_PARAMS_RESET_WAIT_FOR_REPLY)

hal-timecode-frozen-good-responsive-candidate:
	$(MAKE) -B hal \
		HAL_TIMECODE_INPUT_GAIN=1.0f \
		HAL_TIMECODE_INPUT_GATE_THRESHOLD=0.0f \
		HAL_TIMECODE_INPUT_GATE_HOLD_FRAMES=0 \
		HAL_INPUT_MAX_LATENCY_FRAMES=512 \
		HAL_OUTPUT_GAIN=$(HAL_OUTPUT_GAIN) \
		HAL_IDLE_PLAYBACK_GATE_THRESHOLD=0.000001f \
		HAL_IDLE_PLAYBACK_GATE_HOLD_FRAMES=0 \
		HAL_OUTPUT_ZERO_FLOOR=0.0f \
		HAL_BACKGROUND_PREOPEN_ON_INIT=$(HAL_BACKGROUND_PREOPEN_ON_INIT) \
		HAL_STOP_ISOC_ON_STOP=$(HAL_STOP_ISOC_ON_STOP) \
		HAL_RESET_AUDIO_PARAMS_BEFORE_STREAM=$(HAL_RESET_AUDIO_PARAMS_BEFORE_STREAM) \
		HAL_AUDIO_PARAMS_RESET_WAIT_FOR_REPLY=$(HAL_AUDIO_PARAMS_RESET_WAIT_FOR_REPLY)

hal-timecode-responsive-candidate:
	$(MAKE) -B hal \
		HAL_INPUT_MAX_LATENCY_FRAMES=512 \
		HAL_OUTPUT_GAIN=$(HAL_OUTPUT_GAIN) \
		HAL_BACKGROUND_PREOPEN_ON_INIT=$(HAL_BACKGROUND_PREOPEN_ON_INIT) \
		HAL_STOP_ISOC_ON_STOP=$(HAL_STOP_ISOC_ON_STOP) \
		HAL_RESET_AUDIO_PARAMS_BEFORE_STREAM=$(HAL_RESET_AUDIO_PARAMS_BEFORE_STREAM) \
		HAL_AUDIO_PARAMS_RESET_WAIT_FOR_REPLY=$(HAL_AUDIO_PARAMS_RESET_WAIT_FOR_REPLY)

hal-timecode-low-noise-candidate:
	$(MAKE) -B hal \
		HAL_INPUT_MAX_LATENCY_FRAMES=512 \
		HAL_OUTPUT_GAIN=$(HAL_OUTPUT_GAIN) \
		HAL_IDLE_PLAYBACK_GATE_THRESHOLD=0.000001f \
		HAL_IDLE_PLAYBACK_GATE_HOLD_FRAMES=0 \
		HAL_OUTPUT_ZERO_FLOOR=0.0f \
		HAL_BACKGROUND_PREOPEN_ON_INIT=$(HAL_BACKGROUND_PREOPEN_ON_INIT) \
		HAL_STOP_ISOC_ON_STOP=$(HAL_STOP_ISOC_ON_STOP) \
		HAL_RESET_AUDIO_PARAMS_BEFORE_STREAM=$(HAL_RESET_AUDIO_PARAMS_BEFORE_STREAM) \
		HAL_AUDIO_PARAMS_RESET_WAIT_FOR_REPLY=$(HAL_AUDIO_PARAMS_RESET_WAIT_FOR_REPLY)

timecode-latency-e2e-fixture:
	python3 scripts/test-timecode-latency-e2e-fixture.py
	scripts/timecode-latency-e2e-fixture --name baseline --summary-only

timecode-latency-offline-gate:
	$(MAKE) timecode-latency-e2e-fixture
	python3 scripts/test-timecode-latency-offline-gate.py
	./scripts/timecode-latency-offline-gate

$(HAL_FLAGS_STAMP): FORCE
	@mkdir -p build
	@tmp="$@.tmp"; printf '%s\n' '$(HAL_CFLAGS)' > "$$tmp"; \
	if ! cmp -s "$$tmp" "$@"; then \
		mv "$$tmp" "$@"; \
		rm -f $(HAL_BIN); \
	else \
		rm "$$tmp"; \
	fi

$(USB_PLAY_FLAGS_STAMP): FORCE
	@mkdir -p build
	@tmp="$@.tmp"; printf '%s\n' '$(HAL_CFLAGS)' > "$$tmp"; \
	if ! cmp -s "$$tmp" "$@"; then \
		mv "$$tmp" "$@"; \
		rm -f $(USB_PLAY); \
	else \
		rm "$$tmp"; \
	fi

ifeq ($(HAL_PREPARED_USB_SUBMIT_RUNTIME),1)
$(HAL_BIN): $(HAL_SRC) $(HAL_PLIST) $(HAL_FLAGS_STAMP)
	@mkdir -p $(HAL_BUNDLE)/Contents/MacOS $(HAL_PREPARED_OBJ_DIR)
	@install -m 644 $(HAL_PLIST) $(HAL_BUNDLE)/Contents/Info.plist
	xcrun clang $(HAL_CFLAGS) -c src/hal/OpenA8DJHAL.c -o $(HAL_PREPARED_OBJ_DIR)/OpenA8DJHAL.o
	xcrun clang $(HAL_CFLAGS) -c src/hal/OpenA8DJUSB.m -o $(HAL_PREPARED_OBJ_DIR)/OpenA8DJUSB.o
	xcrun clang++ $(HAL_CPP_CFLAGS) -c src/hal/OpenA8DJPreparedRuntimeBridge.mm -o $(HAL_PREPARED_OBJ_DIR)/OpenA8DJPreparedRuntimeBridge.o
	xcrun clang++ $(HAL_CPP_CFLAGS) -c core/src/usb_submit_plan.cpp -o $(HAL_PREPARED_OBJ_DIR)/usb_submit_plan.o
	xcrun clang++ $(HAL_CPP_CFLAGS) -c core/src/usb_request_pool.cpp -o $(HAL_PREPARED_OBJ_DIR)/usb_request_pool.o
	xcrun clang++ $(HAL_CPP_CFLAGS) -c core/src/prepared_usb_async_runtime.cpp -o $(HAL_PREPARED_OBJ_DIR)/prepared_usb_async_runtime.o
	xcrun clang++ -bundle $(HAL_FRAMEWORKS) -o $@ \
		$(HAL_PREPARED_OBJ_DIR)/OpenA8DJHAL.o \
		$(HAL_PREPARED_OBJ_DIR)/OpenA8DJUSB.o \
		$(HAL_PREPARED_OBJ_DIR)/OpenA8DJPreparedRuntimeBridge.o \
		$(HAL_PREPARED_OBJ_DIR)/usb_submit_plan.o \
		$(HAL_PREPARED_OBJ_DIR)/usb_request_pool.o \
		$(HAL_PREPARED_OBJ_DIR)/prepared_usb_async_runtime.o
else
$(HAL_BIN): $(HAL_SRC) $(HAL_PLIST) $(HAL_FLAGS_STAMP)
	@mkdir -p $(HAL_BUNDLE)/Contents/MacOS
	@install -m 644 $(HAL_PLIST) $(HAL_BUNDLE)/Contents/Info.plist
	$(HAL_LD) $(HAL_CFLAGS) -bundle $(HAL_FRAMEWORKS) -o $@ $(HAL_SRC)
endif

sign-hal: $(HAL_BIN)
	rm -rf "$(HAL_BUNDLE)/Contents/_CodeSignature"
	codesign --force --sign "$(SIGN_IDENTITY)" $(CODESIGN_TIMESTAMP) $(CODESIGN_OPTIONS) "$(HAL_BUNDLE)"
	if [ "$(HAL_STAPLE_AFTER_SIGN)" = "1" ]; then xcrun stapler staple "$(HAL_BUNDLE)"; xcrun stapler validate "$(HAL_BUNDLE)"; fi

sign-tools: $(CONTROL_TOOL) $(MIDI_BRIDGE)
	codesign --force --sign "$(SIGN_IDENTITY)" $(CODESIGN_TIMESTAMP) $(CODESIGN_OPTIONS) "$(CONTROL_TOOL)"
	codesign --force --sign "$(SIGN_IDENTITY)" $(CODESIGN_TIMESTAMP) $(CODESIGN_OPTIONS) "$(MIDI_BRIDGE)"

$(HAL_SMOKE): $(HAL_SMOKE_SRC)
	@mkdir -p build
	xcrun clang -Wall -Wextra -Wpedantic -O2 -framework CoreAudio -framework CoreFoundation -o $@ $<

smoke-hal: $(HAL_BIN) $(HAL_SMOKE)
	./$(HAL_SMOKE) $(HAL_BUNDLE)

$(HAL_PARITY_SMOKE): $(HAL_PARITY_SMOKE_SRC)
	@mkdir -p build
	xcrun clang -Wall -Wextra -Wpedantic -O2 -framework CoreAudio -framework CoreFoundation -o $@ $<

parity-smoke-hal: $(HAL_BIN) $(HAL_PARITY_SMOKE)
	./$(HAL_PARITY_SMOKE) $(HAL_BUNDLE)

$(AUDIO_LIST): $(AUDIO_LIST_SRC)
	@mkdir -p build
	xcrun clang -Wall -Wextra -Wpedantic -O2 -framework CoreAudio -framework CoreFoundation -o $@ $<

audio-list: $(AUDIO_LIST)
	./$(AUDIO_LIST)

$(AUDIO_INSPECT): $(AUDIO_INSPECT_SRC)
	@mkdir -p build
	xcrun clang -Wall -Wextra -Wpedantic -O2 -framework CoreAudio -framework CoreFoundation -o $@ $<

audio-inspect: $(AUDIO_INSPECT)
	./$(AUDIO_INSPECT)

$(AUDIO_IO_TEST): $(AUDIO_IO_TEST_SRC)
	@mkdir -p build
	xcrun clang -Wall -Wextra -Wpedantic -O2 -framework CoreAudio -framework CoreFoundation -o $@ $<

audio-io-test: $(AUDIO_IO_TEST)
	./$(AUDIO_IO_TEST)

$(AUDIO_WAV_PLAY): $(AUDIO_WAV_PLAY_SRC)
	@mkdir -p build
	xcrun clang -Wall -Wextra -Wpedantic -O2 -framework CoreAudio -framework CoreFoundation -o $@ $<

audio-wav-play: $(AUDIO_WAV_PLAY)
	./$(AUDIO_WAV_PLAY)

$(AUDIO_RECORD): $(AUDIO_RECORD_SRC)
	@mkdir -p build
	xcrun clang -Wall -Wextra -Wpedantic -O2 -framework CoreAudio -framework CoreFoundation -o $@ $<

audio-record: $(AUDIO_RECORD)
	./$(AUDIO_RECORD)

$(AUDIO_CONFIG): $(AUDIO_CONFIG_SRC)
	@mkdir -p build
	xcrun clang -Wall -Wextra -Wpedantic -O2 -framework CoreAudio -framework CoreFoundation -o $@ $<

audio-config: $(AUDIO_CONFIG)
	./$(AUDIO_CONFIG) org.opena8dj.Audio8DJ 48000 512

$(AUDIO_DEFAULT): $(AUDIO_DEFAULT_SRC)
	@mkdir -p build
	xcrun clang -Wall -Wextra -Wpedantic -O2 -framework CoreAudio -framework CoreFoundation -o $@ $<

audio-default: $(AUDIO_DEFAULT)
	./$(AUDIO_DEFAULT)

$(AUDIO_PAIR_TONE): $(AUDIO_PAIR_TONE_SRC)
	@mkdir -p build
	xcrun clang -Wall -Wextra -Wpedantic -O2 -framework CoreAudio -framework CoreFoundation -framework AudioToolbox -o $@ $<

audio-pair-tone: $(AUDIO_PAIR_TONE)
	./$(AUDIO_PAIR_TONE) A 3 440 0.06

$(AUDIO_ROUTE): $(AUDIO_ROUTE_SRC)
	@mkdir -p build
	xcrun clang -Wall -Wextra -Wpedantic -O2 -framework CoreAudio -framework CoreFoundation -o $@ $<

audio-route: $(AUDIO_ROUTE)
	./$(AUDIO_ROUTE) org.opena8dj.Audio8DJ both

$(INPUT_METER): $(INPUT_METER_SRC)
	@mkdir -p build
	xcrun clang -Wall -Wextra -Wpedantic -O2 -framework CoreAudio -framework CoreFoundation -o $@ $<

audio-input-meter: $(INPUT_METER)
	./$(INPUT_METER) 5

$(MACBOOK_MIC_RECORD): $(MACBOOK_MIC_RECORD_SRC)
	@mkdir -p build
	xcrun clang -Wall -Wextra -Wpedantic -O2 -framework CoreAudio -framework CoreFoundation -framework AudioToolbox -o $@ $<

macbook-mic-record: $(MACBOOK_MIC_RECORD)

audio-stack-health:
	./scripts/audio-stack-health

audio-stack-guard:
	./scripts/audio-stack-guard

audio-stack-recover:
	./scripts/audio-stack-guard --recover --unload-opena8dj

audio-stack-reset:
	./scripts/audio-stack-guard --recover --unload-opena8dj

soundcheck-preflight: $(AUDIO_WAV_PLAY) $(AUDIO_RECORD) $(AUDIO_CONFIG) $(CONTROL_TOOL)
	./scripts/run-soundcheck --skip-build --prepare-only \
		$(if $(SOUNDCHECK_MUSIC),--music-file "$(SOUNDCHECK_MUSIC)",--music-dir "$(SOUNDCHECK_MUSIC_DIR)") \
		--pair "$(SOUNDCHECK_PAIR)" --rate "$(SOUNDCHECK_RATE)" --buffer "$(SOUNDCHECK_BUFFER)" \
		--seconds "$(SOUNDCHECK_PREFLIGHT_SECONDS)" --mode "$(SOUNDCHECK_PREFLIGHT_MODE)"

soundcheck: $(AUDIO_WAV_PLAY) $(AUDIO_RECORD) $(AUDIO_CONFIG) $(CONTROL_TOOL)
	./scripts/run-soundcheck --skip-build \
		$(if $(SOUNDCHECK_MUSIC),--music-file "$(SOUNDCHECK_MUSIC)",--music-dir "$(SOUNDCHECK_MUSIC_DIR)") \
		--pair "$(SOUNDCHECK_PAIR)" --rate "$(SOUNDCHECK_RATE)" --buffer "$(SOUNDCHECK_BUFFER)" \
		--seconds "$(SOUNDCHECK_SECONDS)" --mode "$(SOUNDCHECK_MODE)" \
		--capture-device "$(SOUNDCHECK_CAPTURE)" --capture-channels "$(SOUNDCHECK_CAPTURE_CHANNELS)" \
		--min-alignment "$(SOUNDCHECK_MIN_ALIGNMENT)" \
		--min-snr-db "$(SOUNDCHECK_MIN_SNR_DB)" \
		--max-clicks "$(SOUNDCHECK_MAX_CLICKS)" \
		--max-lag-jumps "$(SOUNDCHECK_MAX_LAG_JUMPS)" \
		--max-mid-band-residual-ratio "$(SOUNDCHECK_MAX_MID_BAND_RESIDUAL_RATIO)" \
		--max-high-band-residual-ratio "$(SOUNDCHECK_MAX_HIGH_BAND_RESIDUAL_RATIO)" \
		--max-quiet-mid-band-noise-dbfs "$(SOUNDCHECK_MAX_QUIET_MID_BAND_NOISE_DBFS)" \
		--max-mid-band-cpu-corr "$(SOUNDCHECK_MAX_MID_BAND_CPU_CORR)" $(if $(filter 1 true yes on,$(SOUNDCHECK_CPU_STRESS)),--cpu-stress --cpu-stress-after "$(SOUNDCHECK_CPU_STRESS_AFTER)" --cpu-stress-seconds "$(SOUNDCHECK_CPU_STRESS_SECONDS)" --cpu-stress-workers "$(SOUNDCHECK_CPU_STRESS_WORKERS)",)

soundcheck-irig-calibrated:
	$(MAKE) soundcheck \
		SOUNDCHECK_PAIR="$(SOUNDCHECK_IRIG_PAIR)" \
		SOUNDCHECK_SECONDS="$(SOUNDCHECK_IRIG_SECONDS)" \
		SOUNDCHECK_MODE="$(SOUNDCHECK_IRIG_MODE)" \
		SOUNDCHECK_MIN_ALIGNMENT="$(SOUNDCHECK_IRIG_MIN_ALIGNMENT)" \
		SOUNDCHECK_MIN_SNR_DB="$(SOUNDCHECK_IRIG_MIN_SNR_DB)" \
		SOUNDCHECK_MAX_CLICKS="$(SOUNDCHECK_IRIG_MAX_CLICKS)" \
		SOUNDCHECK_MAX_LAG_JUMPS="$(SOUNDCHECK_IRIG_MAX_LAG_JUMPS)" \
		SOUNDCHECK_MAX_MID_BAND_RESIDUAL_RATIO="$(SOUNDCHECK_IRIG_MAX_MID_BAND_RESIDUAL_RATIO)" \
		SOUNDCHECK_MAX_HIGH_BAND_RESIDUAL_RATIO="$(SOUNDCHECK_IRIG_MAX_HIGH_BAND_RESIDUAL_RATIO)" \
		SOUNDCHECK_MAX_QUIET_MID_BAND_NOISE_DBFS="$(SOUNDCHECK_IRIG_MAX_QUIET_MID_BAND_NOISE_DBFS)" \
		SOUNDCHECK_MAX_MID_BAND_CPU_CORR="$(SOUNDCHECK_IRIG_MAX_MID_BAND_CPU_CORR)"

direct-usb-soundcheck: $(USB_PLAY) $(AUDIO_RECORD)
	./scripts/run-direct-usb-soundcheck --skip-build \
		$(if $(SOUNDCHECK_MUSIC),--music-file "$(SOUNDCHECK_MUSIC)",--music-dir "$(SOUNDCHECK_MUSIC_DIR)") \
		--pair "$(SOUNDCHECK_PAIR)" --rate "$(SOUNDCHECK_RATE)" \
		--seconds "$(SOUNDCHECK_SECONDS)" --mode "$(SOUNDCHECK_MODE)" \
		--target-peak-db "$(SOUNDCHECK_TARGET_PEAK_DB)" \
		--capture-device "$(SOUNDCHECK_CAPTURE)" --capture-channels "$(SOUNDCHECK_CAPTURE_CHANNELS)" \
		--lead-frames "$(DIRECT_USB_LEAD_FRAMES)" \
		--player "$(DIRECT_USB_PLAYER)"

simulated-output-soundcheck:
	./scripts/run-simulated-output-soundcheck \
		$(if $(SOUNDCHECK_MUSIC),--music-file "$(SOUNDCHECK_MUSIC)",--music-dir "$(SOUNDCHECK_MUSIC_DIR)") \
		--pair "$(SIM_OUTPUT_PAIR)" --rate "$(SOUNDCHECK_RATE)" \
		--seconds "$(SIM_OUTPUT_SECONDS)" --mode "$(SIM_OUTPUT_MODE)" \
		--gain "$(SIM_OUTPUT_GAIN)" \
		--max-mid-band-residual-ratio "$(SOUNDCHECK_MAX_MID_BAND_RESIDUAL_RATIO)" \
		--max-mid-band-cpu-corr "$(SOUNDCHECK_MAX_MID_BAND_CPU_CORR)"

channel-matrix-prepare:
	./scripts/run-channel-matrix-gate \
		--pair "$(CHANNEL_MATRIX_PAIR)" --rate "$(CHANNEL_MATRIX_RATE)" \
		--seconds "$(CHANNEL_MATRIX_SECONDS)" --peak "$(CHANNEL_MATRIX_PEAK)"

$(USB_PLAY): $(USB_PLAY_SRC) src/hal/OpenA8DJUSB.m src/hal/OpenA8DJUSB.h $(USB_PLAY_FLAGS_STAMP)
	@mkdir -p build
	$(CC) $(HAL_CFLAGS) -framework Foundation -framework IOKit -framework IOUSBHost -framework CoreMIDI -framework CoreAudio -framework CoreFoundation -o $@ $(USB_PLAY_SRC) src/hal/OpenA8DJUSB.m

usb-play: $(USB_PLAY)

$(USB_PLAY_PLAIN): $(USB_PLAY_SRC) src/hal/OpenA8DJUSB.m src/hal/OpenA8DJUSB.h
	@mkdir -p build
	$(CC) $(CFLAGS) -framework Foundation -framework IOKit -framework IOUSBHost -framework CoreMIDI -framework CoreAudio -framework CoreFoundation -o $@ $(USB_PLAY_SRC) src/hal/OpenA8DJUSB.m

usb-play-plain: $(USB_PLAY_PLAIN)

$(USB_PLAY_PLAIN_GAIN05): $(USB_PLAY_SRC) src/hal/OpenA8DJUSB.m src/hal/OpenA8DJUSB.h
	@mkdir -p build
	$(CC) $(CFLAGS) -DOPENA8DJ_OUTPUT_GAIN=0.50f -framework Foundation -framework IOKit -framework IOUSBHost -framework CoreMIDI -framework CoreAudio -framework CoreFoundation -o $@ $(USB_PLAY_SRC) src/hal/OpenA8DJUSB.m

usb-play-plain-gain05: $(USB_PLAY_PLAIN_GAIN05)

$(USB_INPUT_METER): $(USB_INPUT_METER_SRC) src/hal/OpenA8DJUSB.m src/hal/OpenA8DJUSB.h
	@mkdir -p build
	$(CC) $(CFLAGS) -framework Foundation -framework IOKit -framework IOUSBHost -framework CoreMIDI -framework CoreAudio -framework CoreFoundation -o $@ $(USB_INPUT_METER_SRC) src/hal/OpenA8DJUSB.m

usb-input-meter: $(USB_INPUT_METER)
	./$(USB_INPUT_METER) 6 48000

$(MIDI_BRIDGE): $(MIDI_BRIDGE_SRC)
	@mkdir -p build
	xcrun clang $(CFLAGS) $(MIDI_FRAMEWORKS) -o $@ $<

$(CONTROL_TOOL): $(CONTROL_TOOL_SRC) src/hal/OpenA8DJUSB.m
	@mkdir -p build
	xcrun clang -Wall -Wextra -Wpedantic -O2 -framework CoreAudio -framework CoreFoundation -o $@ $<

$(CONTROL_CENTER_APP): $(CONTROL_CENTER_SRC) $(CONTROL_CENTER_PLIST) $(CONTROL_TOOL)
	rm -rf "$(CONTROL_CENTER_APP)"
	mkdir -p "$(CONTROL_CENTER_APP)/Contents/MacOS" "$(CONTROL_CENTER_APP)/Contents/Resources"
	cp "$(CONTROL_CENTER_PLIST)" "$(CONTROL_CENTER_APP)/Contents/Info.plist"
	cp "$(CONTROL_TOOL)" "$(CONTROL_CENTER_APP)/Contents/Resources/opena8dj-control"
	xcrun swiftc -parse-as-library -O -framework SwiftUI -framework AppKit -o "$(CONTROL_CENTER_APP)/Contents/MacOS/OpenA8DJControlCenter" "$(CONTROL_CENTER_SRC)"
	codesign --force --deep --sign "$(SIGN_IDENTITY)" $(CODESIGN_TIMESTAMP) $(CODESIGN_OPTIONS) "$(CONTROL_CENTER_APP)"

control-center: $(CONTROL_CENTER_APP)

$(MIDI_LIST): $(MIDI_LIST_SRC)
	@mkdir -p build
	xcrun clang -Wall -Wextra -Wpedantic -O2 -framework CoreMIDI -framework CoreFoundation -o $@ $<

midi-list: $(MIDI_LIST)
	./$(MIDI_LIST)

$(PHYSICAL_RUN_COMPARE): $(PHYSICAL_RUN_COMPARE_SRC)
	@mkdir -p build
	xcrun clang++ -std=c++20 -Wall -Wextra -Wpedantic -O2 -o $@ $<

physical-run-compare: $(PHYSICAL_RUN_COMPARE)
	./$(PHYSICAL_RUN_COMPARE) local-analysis/soundcheck/20260617-streamusage-irig-pairA-12s-cpp-hal

install-hal: sign-hal
	sudo install -d /Library/Audio/Plug-Ins/HAL
	sudo rm -rf /Library/Audio/Plug-Ins/HAL/OpenA8DJ.driver
	sudo cp -R $(HAL_BUNDLE) /Library/Audio/Plug-Ins/HAL/OpenA8DJ.driver
	sudo xattr -cr /Library/Audio/Plug-Ins/HAL/OpenA8DJ.driver
	sudo codesign --force --sign "$(SIGN_IDENTITY)" $(CODESIGN_TIMESTAMP) $(CODESIGN_OPTIONS) /Library/Audio/Plug-Ins/HAL/OpenA8DJ.driver
	sudo killall coreaudiod || true

install-tools: $(CONTROL_TOOL)
	sudo install -d /usr/local/bin
	sudo install -m 755 $(CONTROL_TOOL) /usr/local/bin/opena8dj-control

install-control-surfaces: $(CONTROL_CENTER_APP)
	sudo install -d /usr/local/bin /Applications /Library/Documentation/OpenA8DJ/ControlSurfaces
	sudo install -m 755 $(CONTROL_TOOL) /usr/local/bin/opena8dj-control
	sudo rm -rf "/Applications/OpenA8DJ Control Center.app"
	COPYFILE_DISABLE=1 sudo cp -R "$(CONTROL_CENTER_APP)" "/Applications/OpenA8DJ Control Center.app"
	sudo install -m 644 docs/user/control-center.md /Library/Documentation/OpenA8DJ/ControlSurfaces/USER_GUIDE.md
	sudo install -m 644 docs/user/traktor-timecode.md /Library/Documentation/OpenA8DJ/ControlSurfaces/TRAKTOR_TIMECODE.md
	sudo install -m 644 docs/project/cabling.md /Library/Documentation/OpenA8DJ/ControlSurfaces/CABLING.md
	sudo install -m 755 "$(CONTROL_PKG_SCRIPTS)/uninstall-opena8dj-control-surfaces.sh" /Library/Documentation/OpenA8DJ/ControlSurfaces/uninstall-opena8dj-control-surfaces.sh
	sudo xattr -cr "/Applications/OpenA8DJ Control Center.app" /Library/Documentation/OpenA8DJ/ControlSurfaces 2>/dev/null || true

install-midid: $(MIDI_BRIDGE) $(LAUNCH_AGENT_PLIST)
	sudo install -d /usr/local/bin
	sudo install -m 755 $(MIDI_BRIDGE) /usr/local/bin/opena8dj-midid
	sudo install -d /Library/LaunchAgents
	sudo install -m 644 $(LAUNCH_AGENT_PLIST) /Library/LaunchAgents/org.opena8dj.midid.plist
	launchctl bootout gui/$$(id -u) "$$HOME/Library/LaunchAgents/org.opena8dj.midid.plist" 2>/dev/null || true
	rm -f "$$HOME/Library/LaunchAgents/org.opena8dj.midid.plist"
	launchctl bootout gui/$$(id -u) /Library/LaunchAgents/org.opena8dj.midid.plist 2>/dev/null || true
	launchctl bootstrap gui/$$(id -u) /Library/LaunchAgents/org.opena8dj.midid.plist
	launchctl kickstart -k gui/$$(id -u)/org.opena8dj.midid

package: all sign-hal sign-tools $(CONTROL_CENTER_APP)
	rm -rf $(PKG_ROOT)
	install -d "$(PKG_ROOT)/Library/Audio/Plug-Ins/HAL"
	COPYFILE_DISABLE=1 cp -R "$(HAL_BUNDLE)" "$(PKG_ROOT)/Library/Audio/Plug-Ins/HAL/OpenA8DJ.driver"
	install -d "$(PKG_ROOT)/Applications"
	COPYFILE_DISABLE=1 cp -R "$(CONTROL_CENTER_APP)" "$(PKG_ROOT)/Applications/OpenA8DJ Control Center.app"
	install -d "$(PKG_ROOT)/usr/local/bin"
	install -m 755 "$(CONTROL_TOOL)" "$(PKG_ROOT)/usr/local/bin/opena8dj-control"
	install -m 755 "$(MIDI_BRIDGE)" "$(PKG_ROOT)/usr/local/bin/opena8dj-midid"
	install -m 755 "$(PKG_SCRIPTS)/uninstall-opena8dj.sh" "$(PKG_ROOT)/usr/local/bin/opena8dj-uninstall"
	install -d "$(PKG_ROOT)/Library/LaunchAgents"
	install -m 644 "$(LAUNCH_AGENT_PLIST)" "$(PKG_ROOT)/Library/LaunchAgents/org.opena8dj.midid.plist"
	install -d "$(PKG_ROOT)/Library/Documentation/OpenA8DJ"
	install -m 644 LICENSE "$(PKG_ROOT)/Library/Documentation/OpenA8DJ/LICENSE"
	install -m 644 NOTICE.md "$(PKG_ROOT)/Library/Documentation/OpenA8DJ/NOTICE.md"
	install -m 644 docs/reference/legal.md "$(PKG_ROOT)/Library/Documentation/OpenA8DJ/LEGAL.md"
	install -m 644 BRAND_POLICY.md "$(PKG_ROOT)/Library/Documentation/OpenA8DJ/BRAND_POLICY.md"
	if [ -f "$(RELEASE_NOTES)" ]; then install -m 644 "$(RELEASE_NOTES)" "$(PKG_ROOT)/Library/Documentation/OpenA8DJ/RELEASE_NOTES.md"; fi
	install -d "$(PKG_ROOT)/Library/Documentation/OpenA8DJ/ControlSurfaces"
	install -m 644 docs/user/control-center.md "$(PKG_ROOT)/Library/Documentation/OpenA8DJ/ControlSurfaces/USER_GUIDE.md"
	install -m 644 docs/user/traktor-timecode.md "$(PKG_ROOT)/Library/Documentation/OpenA8DJ/ControlSurfaces/TRAKTOR_TIMECODE.md"
	install -m 644 docs/project/cabling.md "$(PKG_ROOT)/Library/Documentation/OpenA8DJ/ControlSurfaces/CABLING.md"
	chmod +x "$(PKG_SCRIPTS)/preinstall" "$(PKG_SCRIPTS)/postinstall" "$(PKG_SCRIPTS)/uninstall-opena8dj.sh"
	xattr -cr "$(PKG_ROOT)" 2>/dev/null || true
	find "$(PKG_ROOT)" -name '._*' -delete
	COPYFILE_DISABLE=1 pkgbuild --analyze --root "$(PKG_ROOT)" "$(PKG_COMPONENTS)"
	plutil -replace 0.BundleIsRelocatable -bool NO "$(PKG_COMPONENTS)"
	plutil -replace 1.BundleIsRelocatable -bool NO "$(PKG_COMPONENTS)"
	COPYFILE_DISABLE=1 pkgbuild --root "$(PKG_ROOT)" --component-plist "$(PKG_COMPONENTS)" --scripts "$(PKG_SCRIPTS)" --identifier org.opena8dj.driver --version "$(VERSION)" --install-location / --filter '(^|/)\._.*' --filter '(^|/)\.DS_Store$$' $(if $(PKG_SIGN_IDENTITY),--sign "$(PKG_SIGN_IDENTITY)") "$(PKG)"
	if [ -z "$(PKG_SIGN_IDENTITY)" ]; then "$(PKG_SANITIZER)" "$(PKG)" "$(PKG_ROOT)" "$(PKG_SCRIPTS)"; fi

control-surfaces-package: $(CONTROL_CENTER_APP)
	rm -rf "$(CONTROL_PKG_ROOT)"
	install -d "$(CONTROL_PKG_ROOT)/Applications"
	COPYFILE_DISABLE=1 cp -R "$(CONTROL_CENTER_APP)" "$(CONTROL_PKG_ROOT)/Applications/OpenA8DJ Control Center.app"
	install -d "$(CONTROL_PKG_ROOT)/usr/local/bin"
	install -m 755 "$(CONTROL_TOOL)" "$(CONTROL_PKG_ROOT)/usr/local/bin/opena8dj-control"
	install -d "$(CONTROL_PKG_ROOT)/Library/Documentation/OpenA8DJ/ControlSurfaces"
	install -m 644 docs/user/control-center.md "$(CONTROL_PKG_ROOT)/Library/Documentation/OpenA8DJ/ControlSurfaces/USER_GUIDE.md"
	install -m 644 docs/user/traktor-timecode.md "$(CONTROL_PKG_ROOT)/Library/Documentation/OpenA8DJ/ControlSurfaces/TRAKTOR_TIMECODE.md"
	install -m 644 docs/project/cabling.md "$(CONTROL_PKG_ROOT)/Library/Documentation/OpenA8DJ/ControlSurfaces/CABLING.md"
	install -m 644 LICENSE "$(CONTROL_PKG_ROOT)/Library/Documentation/OpenA8DJ/ControlSurfaces/LICENSE"
	install -m 644 NOTICE.md "$(CONTROL_PKG_ROOT)/Library/Documentation/OpenA8DJ/ControlSurfaces/NOTICE.md"
	install -m 644 docs/reference/legal.md "$(CONTROL_PKG_ROOT)/Library/Documentation/OpenA8DJ/ControlSurfaces/LEGAL.md"
	install -m 644 BRAND_POLICY.md "$(CONTROL_PKG_ROOT)/Library/Documentation/OpenA8DJ/ControlSurfaces/BRAND_POLICY.md"
	install -m 755 "$(CONTROL_PKG_SCRIPTS)/uninstall-opena8dj-control-surfaces.sh" "$(CONTROL_PKG_ROOT)/Library/Documentation/OpenA8DJ/ControlSurfaces/uninstall-opena8dj-control-surfaces.sh"
	chmod +x "$(CONTROL_PKG_SCRIPTS)/preinstall" "$(CONTROL_PKG_SCRIPTS)/postinstall" "$(CONTROL_PKG_SCRIPTS)/uninstall-opena8dj-control-surfaces.sh"
	xattr -cr "$(CONTROL_PKG_ROOT)" 2>/dev/null || true
	find "$(CONTROL_PKG_ROOT)" -name '._*' -delete
	COPYFILE_DISABLE=1 pkgbuild --analyze --root "$(CONTROL_PKG_ROOT)" "$(CONTROL_PKG_COMPONENTS)"
	plutil -replace 0.BundleIsRelocatable -bool NO "$(CONTROL_PKG_COMPONENTS)"
	COPYFILE_DISABLE=1 pkgbuild --root "$(CONTROL_PKG_ROOT)" --component-plist "$(CONTROL_PKG_COMPONENTS)" --scripts "$(CONTROL_PKG_SCRIPTS)" --identifier org.opena8dj.tools --version "$(VERSION)" --install-location / --filter '(^|/)\._.*' --filter '(^|/)\.DS_Store$$' $(if $(PKG_SIGN_IDENTITY),--sign "$(PKG_SIGN_IDENTITY)") "$(CONTROL_PKG)"
	if [ -z "$(PKG_SIGN_IDENTITY)" ]; then "$(PKG_SANITIZER)" "$(CONTROL_PKG)" "$(CONTROL_PKG_ROOT)" "$(CONTROL_PKG_SCRIPTS)"; fi

tools-package: control-surfaces-package

dmg: package $(DMG_README)
	rm -rf "$(DMG_ROOT)" "$(DMG)"
	install -d "$(DMG_ROOT)"
	install -m 644 "$(PKG)" "$(DMG_ROOT)/OpenA8DJ-$(VERSION).pkg"
	install -m 644 "$(DMG_README)" "$(DMG_ROOT)/README.txt"
	install -m 644 LICENSE "$(DMG_ROOT)/LICENSE"
	install -m 644 NOTICE.md "$(DMG_ROOT)/NOTICE.md"
	install -m 644 docs/reference/legal.md "$(DMG_ROOT)/LEGAL.md"
	install -m 644 BRAND_POLICY.md "$(DMG_ROOT)/BRAND_POLICY.md"
	if [ -f "$(RELEASE_NOTES)" ]; then install -m 644 "$(RELEASE_NOTES)" "$(DMG_ROOT)/RELEASE_NOTES.md"; fi
	hdiutil create -volname "OpenA8DJ $(VERSION)" -srcfolder "$(DMG_ROOT)" -ov -format UDZO "$(DMG)"
	if [ -n "$(DMG_SIGN_IDENTITY)" ]; then codesign --force --sign "$(DMG_SIGN_IDENTITY)" --timestamp "$(DMG)"; fi

control-surfaces-dmg: control-surfaces-package $(CONTROL_DMG_README)
	rm -rf "$(CONTROL_DMG_ROOT)" "$(CONTROL_DMG)"
	install -d "$(CONTROL_DMG_ROOT)"
	install -m 644 "$(CONTROL_PKG)" "$(CONTROL_DMG_ROOT)/opena8dj-tools-$(VERSION).pkg"
	install -m 644 "$(CONTROL_DMG_README)" "$(CONTROL_DMG_ROOT)/README.txt"
	install -m 644 docs/user/control-center.md "$(CONTROL_DMG_ROOT)/CONTROL_SURFACES_USER_GUIDE.md"
	install -m 644 docs/user/traktor-timecode.md "$(CONTROL_DMG_ROOT)/TRAKTOR_TIMECODE.md"
	install -m 644 docs/project/cabling.md "$(CONTROL_DMG_ROOT)/CABLING.md"
	install -m 644 LICENSE "$(CONTROL_DMG_ROOT)/LICENSE"
	install -m 644 NOTICE.md "$(CONTROL_DMG_ROOT)/NOTICE.md"
	install -m 644 docs/reference/legal.md "$(CONTROL_DMG_ROOT)/LEGAL.md"
	install -m 644 BRAND_POLICY.md "$(CONTROL_DMG_ROOT)/BRAND_POLICY.md"
	hdiutil create -volname "opena8dj-tools $(VERSION)" -srcfolder "$(CONTROL_DMG_ROOT)" -ov -format UDZO "$(CONTROL_DMG)"
	if [ -n "$(DMG_SIGN_IDENTITY)" ]; then codesign --force --sign "$(DMG_SIGN_IDENTITY)" --timestamp "$(CONTROL_DMG)"; fi

tools-dmg: control-surfaces-dmg

driver-checksums: dmg
	(cd build && shasum -a 256 "OpenA8DJ-$(VERSION).dmg" > "OpenA8DJ-$(VERSION)-checksums.txt")

driver-dist: driver-checksums

checksums: dmg control-surfaces-dmg
	(cd build && shasum -a 256 "OpenA8DJ-$(VERSION).dmg" "OpenA8DJ-$(VERSION).pkg" "opena8dj-tools-$(VERSION).dmg" "opena8dj-tools-$(VERSION).pkg" > "OpenA8DJ-$(VERSION)-checksums.txt")

dist: checksums

release-signed:
	@test "$(SIGN_IDENTITY)" != "-" || (echo "SIGN_IDENTITY must be a Developer ID Application identity" >&2; exit 2)
	@test -n "$(PKG_SIGN_IDENTITY)" || (echo "PKG_SIGN_IDENTITY must be a Developer ID Installer identity" >&2; exit 2)
	@test -n "$(DMG_SIGN_IDENTITY)" || (echo "DMG_SIGN_IDENTITY must be a Developer ID Application identity" >&2; exit 2)
	$(MAKE) dist CODESIGN_TIMESTAMP=--timestamp CODESIGN_OPTIONS="--options runtime"

notarize:
	VERSION="$(VERSION)" PKG="$(PKG)" DMG="$(DMG)" CHECKSUMS="$(CHECKSUMS)" NOTARY_PROFILE="$(NOTARY_PROFILE)" DMG_SIGN_IDENTITY="$(DMG_SIGN_IDENTITY)" ./scripts/notarize-release

verify-signed-release:
	VERSION="$(VERSION)" PKG="$(PKG)" DMG="$(DMG)" CHECKSUMS="$(CHECKSUMS)" HAL_BUNDLE="$(HAL_BUNDLE)" CONTROL_TOOL="$(CONTROL_TOOL)" MIDI_BRIDGE="$(MIDI_BRIDGE)" ./scripts/verify-signed-release

probe: $(TOOL)
	./$(TOOL)

claim: $(TOOL)
	./$(TOOL) --claim

clean:
	rm -rf build
