#ifndef OPENA8DJ_MIDI_BUS_CONTRACT_H
#define OPENA8DJ_MIDI_BUS_CONTRACT_H

#if defined(_KERNEL_MODE)
#include <ntdef.h>
typedef USHORT OPENA8DJ_MIDI_UINT16;
typedef ULONG OPENA8DJ_MIDI_UINT32;
#else
#include <stddef.h>
#include <stdint.h>
typedef uint16_t OPENA8DJ_MIDI_UINT16;
typedef uint32_t OPENA8DJ_MIDI_UINT32;
#endif

#ifdef __cplusplus
extern "C" {
#endif

#define OPENA8DJ_MIDI_BUS_INTERFACE_MAGIC 0x4a443841u
#define OPENA8DJ_MIDI_BUS_INTERFACE_VERSION_V1 1u
#define OPENA8DJ_MIDI_BUS_INTERFACE_V1_X64_SIZE 80u

/* S1 supports the legacy PortCls MIDI path on Windows 10 2004+ x64. */
#define OPENA8DJ_MIDI_MINIMUM_WINDOWS_BUILD 19041u

#define OPENA8DJ_MIDI_BUS_CAP_RAW_BYTES 0x00000001u
#define OPENA8DJ_MIDI_BUS_CAP_NONBLOCKING_IO 0x00000002u
#define OPENA8DJ_MIDI_BUS_CAP_ATOMIC_WRITE 0x00000004u
#define OPENA8DJ_MIDI_BUS_CAP_SYNCHRONOUS_QUERY 0x00000008u
#define OPENA8DJ_MIDI_BUS_REQUIRED_CAPABILITIES \
    (OPENA8DJ_MIDI_BUS_CAP_RAW_BYTES | \
     OPENA8DJ_MIDI_BUS_CAP_NONBLOCKING_IO | \
     OPENA8DJ_MIDI_BUS_CAP_ATOMIC_WRITE | \
     OPENA8DJ_MIDI_BUS_CAP_SYNCHRONOUS_QUERY)

/*
 * The parent must persist these checkpoints in its own diagnostic state while
 * servicing IRP_MN_QUERY_INTERFACE. Completion must occur before its dispatch
 * routine returns; returning STATUS_PENDING violates V1.
 */
#define OPENA8DJ_MIDI_PARENT_QUERY_CHECKPOINT_ENTERED 0x4d490101u
#define OPENA8DJ_MIDI_PARENT_QUERY_CHECKPOINT_REFERENCED 0x4d490102u
#define OPENA8DJ_MIDI_PARENT_QUERY_CHECKPOINT_COMPLETED 0x4d490103u

/* Child-side checkpoints are kept in g_OpenA8DJMidiQueryInterfaceCheckpoint. */
#define OPENA8DJ_MIDI_CHILD_QUERY_CHECKPOINT_NOT_STARTED 0x4d490200u
#define OPENA8DJ_MIDI_CHILD_QUERY_CHECKPOINT_CALLING_PARENT 0x4d490201u
#define OPENA8DJ_MIDI_CHILD_QUERY_CHECKPOINT_PENDING_VIOLATION 0x4d490202u
#define OPENA8DJ_MIDI_CHILD_QUERY_CHECKPOINT_COMPLETED 0x4d490203u
#define OPENA8DJ_MIDI_CHILD_QUERY_CHECKPOINT_VALIDATED 0x4d490204u

#define OPENA8DJ_MIDI_BUS_FUNCTION_OPEN 0x00000001u
#define OPENA8DJ_MIDI_BUS_FUNCTION_CLOSE 0x00000002u
#define OPENA8DJ_MIDI_BUS_FUNCTION_SET_STATE 0x00000004u
#define OPENA8DJ_MIDI_BUS_FUNCTION_READ 0x00000008u
#define OPENA8DJ_MIDI_BUS_FUNCTION_WRITE 0x00000010u
#define OPENA8DJ_MIDI_BUS_REQUIRED_FUNCTIONS \
    (OPENA8DJ_MIDI_BUS_FUNCTION_OPEN | \
     OPENA8DJ_MIDI_BUS_FUNCTION_CLOSE | \
     OPENA8DJ_MIDI_BUS_FUNCTION_SET_STATE | \
     OPENA8DJ_MIDI_BUS_FUNCTION_READ | \
     OPENA8DJ_MIDI_BUS_FUNCTION_WRITE)

typedef struct OPENA8DJ_MIDI_BUS_CONTRACT_VIEW {
    OPENA8DJ_MIDI_UINT16 size;
    OPENA8DJ_MIDI_UINT16 requiredSize;
    OPENA8DJ_MIDI_UINT16 version;
    OPENA8DJ_MIDI_UINT16 reserved;
    OPENA8DJ_MIDI_UINT32 magic;
    OPENA8DJ_MIDI_UINT32 capabilities;
    OPENA8DJ_MIDI_UINT32 functions;
} OPENA8DJ_MIDI_BUS_CONTRACT_VIEW;

typedef enum OPENA8DJ_MIDI_BUS_CONTRACT_RESULT {
    OPENA8DJ_MIDI_BUS_CONTRACT_OK = 0,
    OPENA8DJ_MIDI_BUS_CONTRACT_NULL,
    OPENA8DJ_MIDI_BUS_CONTRACT_SIZE,
    OPENA8DJ_MIDI_BUS_CONTRACT_VERSION,
    OPENA8DJ_MIDI_BUS_CONTRACT_MAGIC,
    OPENA8DJ_MIDI_BUS_CONTRACT_CAPABILITIES,
    OPENA8DJ_MIDI_BUS_CONTRACT_FUNCTIONS
} OPENA8DJ_MIDI_BUS_CONTRACT_RESULT;

typedef enum OPENA8DJ_MIDI_BUS_WRITE_STATUS_CLASS {
    OPENA8DJ_MIDI_BUS_WRITE_STATUS_SUCCESS = 0,
    OPENA8DJ_MIDI_BUS_WRITE_STATUS_BUSY,
    OPENA8DJ_MIDI_BUS_WRITE_STATUS_FAILURE
} OPENA8DJ_MIDI_BUS_WRITE_STATUS_CLASS;

typedef enum OPENA8DJ_MIDI_PORTCLS_WRITE_ACTION {
    OPENA8DJ_MIDI_PORTCLS_WRITE_COMPLETE = 0,
    OPENA8DJ_MIDI_PORTCLS_WRITE_BACKPRESSURE,
    OPENA8DJ_MIDI_PORTCLS_WRITE_TRANSPORT_ERROR,
    OPENA8DJ_MIDI_PORTCLS_WRITE_PROTOCOL_ERROR
} OPENA8DJ_MIDI_PORTCLS_WRITE_ACTION;

OPENA8DJ_MIDI_BUS_CONTRACT_RESULT
OpenA8DJMidiValidateBusContract(
    const OPENA8DJ_MIDI_BUS_CONTRACT_VIEW *contractView);

OPENA8DJ_MIDI_PORTCLS_WRITE_ACTION
OpenA8DJMidiClassifyBusWriteResult(
    OPENA8DJ_MIDI_BUS_WRITE_STATUS_CLASS statusClass,
    OPENA8DJ_MIDI_UINT32 requestedBytes,
    OPENA8DJ_MIDI_UINT32 reportedBytes);

#ifdef __cplusplus
}
#endif

#endif
