#pragma once

#ifdef __cplusplus
extern "C" {
#endif

#ifndef OPENA8DJ_CTL_BASE
#define OPENA8DJ_CTL_BASE 0x800
#endif

#define OPENA8DJ_DRIVER_API_VERSION 1

#define OPENA8DJ_VENDOR_ID 0x17CC
#define OPENA8DJ_PRODUCT_ID 0x1978

#define OPENA8DJ_INPUT_CHANNELS 8
#define OPENA8DJ_OUTPUT_CHANNELS 8
#define OPENA8DJ_STEREO_PAIRS 4
#define OPENA8DJ_SAMPLE_RATE_COUNT 4
#define OPENA8DJ_CHANNEL_NAME_LENGTH 32

#define OPENA8DJ_DEFAULT_SAMPLE_RATE 48000
#define OPENA8DJ_DEFAULT_BUFFER_FRAMES 512
#define OPENA8DJ_MIN_BUFFER_FRAMES 15
#define OPENA8DJ_MAX_BUFFER_FRAMES 4096

#define OPENA8DJ_PROFILE_TIMECODE_VINYL 0
#define OPENA8DJ_PROFILE_TIMECODE_CD_LINE 1
#define OPENA8DJ_PROFILE_PHONO 2
#define OPENA8DJ_PROFILE_UNLOCK 3

DEFINE_GUID(GUID_DEVINTERFACE_OPENA8DJ_USB,
    0xa3ca3315, 0x46ee, 0x416b, 0xbe, 0x25, 0xfb, 0x52, 0xf3, 0xd8, 0x44, 0x22);

#define IOCTL_OPENA8DJ_GET_USB_INFO \
    CTL_CODE(FILE_DEVICE_UNKNOWN, OPENA8DJ_CTL_BASE + 0, METHOD_BUFFERED, FILE_READ_DATA)
#define IOCTL_OPENA8DJ_GET_CAPABILITIES \
    CTL_CODE(FILE_DEVICE_UNKNOWN, OPENA8DJ_CTL_BASE + 1, METHOD_BUFFERED, FILE_READ_DATA)
#define IOCTL_OPENA8DJ_GET_CONTROL_STATE \
    CTL_CODE(FILE_DEVICE_UNKNOWN, OPENA8DJ_CTL_BASE + 2, METHOD_BUFFERED, FILE_READ_DATA)
#define IOCTL_OPENA8DJ_SET_CONTROL_STATE \
    CTL_CODE(FILE_DEVICE_UNKNOWN, OPENA8DJ_CTL_BASE + 3, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_OPENA8DJ_APPLY_PROFILE \
    CTL_CODE(FILE_DEVICE_UNKNOWN, OPENA8DJ_CTL_BASE + 4, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_OPENA8DJ_GET_AUDIO_FORMAT \
    CTL_CODE(FILE_DEVICE_UNKNOWN, OPENA8DJ_CTL_BASE + 5, METHOD_BUFFERED, FILE_READ_DATA)
#define IOCTL_OPENA8DJ_SET_AUDIO_FORMAT \
    CTL_CODE(FILE_DEVICE_UNKNOWN, OPENA8DJ_CTL_BASE + 6, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_OPENA8DJ_START_STREAMING \
    CTL_CODE(FILE_DEVICE_UNKNOWN, OPENA8DJ_CTL_BASE + 7, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_OPENA8DJ_STOP_STREAMING \
    CTL_CODE(FILE_DEVICE_UNKNOWN, OPENA8DJ_CTL_BASE + 8, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_OPENA8DJ_GET_STREAM_STATE \
    CTL_CODE(FILE_DEVICE_UNKNOWN, OPENA8DJ_CTL_BASE + 9, METHOD_BUFFERED, FILE_READ_DATA)

typedef struct _OPENA8DJ_USB_INFO {
    ULONG Size;
    USHORT VendorId;
    USHORT ProductId;
    UCHAR ConfiguredInterfaceCount;
    BOOLEAN HasBulkOut;
    BOOLEAN HasBulkIn;
    BOOLEAN HasIsoIn;
    BOOLEAN HasIsoOut;
} OPENA8DJ_USB_INFO, *POPENA8DJ_USB_INFO;

typedef struct _OPENA8DJ_CAPABILITIES {
    ULONG Size;
    ULONG ApiVersion;
    USHORT VendorId;
    USHORT ProductId;
    UCHAR InputChannels;
    UCHAR OutputChannels;
    UCHAR StereoPairs;
    UCHAR MidiInputs;
    UCHAR MidiOutputs;
    ULONG SampleRates[OPENA8DJ_SAMPLE_RATE_COUNT];
    ULONG MinBufferFrames;
    ULONG MaxBufferFrames;
    ULONG DefaultBufferFrames;
    CHAR InputPairNames[OPENA8DJ_STEREO_PAIRS][OPENA8DJ_CHANNEL_NAME_LENGTH];
    CHAR OutputPairNames[OPENA8DJ_STEREO_PAIRS][OPENA8DJ_CHANNEL_NAME_LENGTH];
    BOOLEAN Experimental;
    BOOLEAN WindowsAudioEndpointExposed;
    BOOLEAN UsbTransportReady;
    BOOLEAN MidiReady;
    BOOLEAN ControlsReady;
} OPENA8DJ_CAPABILITIES, *POPENA8DJ_CAPABILITIES;

typedef struct _OPENA8DJ_CONTROL_STATE {
    ULONG Size;
    UCHAR InputMode;
    UCHAR GndLiftTCVinyl;
    UCHAR GndLiftTCCDLine;
    UCHAR GndLiftPhono;
    UCHAR SoftwareLock;
} OPENA8DJ_CONTROL_STATE, *POPENA8DJ_CONTROL_STATE;

typedef struct _OPENA8DJ_PROFILE_REQUEST {
    ULONG Size;
    ULONG Profile;
} OPENA8DJ_PROFILE_REQUEST, *POPENA8DJ_PROFILE_REQUEST;

typedef struct _OPENA8DJ_AUDIO_FORMAT {
    ULONG Size;
    ULONG SampleRate;
    ULONG InputChannels;
    ULONG OutputChannels;
    ULONG BufferFrames;
} OPENA8DJ_AUDIO_FORMAT, *POPENA8DJ_AUDIO_FORMAT;

typedef struct _OPENA8DJ_STREAM_STATE {
    ULONG Size;
    BOOLEAN Streaming;
    ULONG SampleRate;
    ULONG BufferFrames;
    ULONG64 RenderFramesSubmitted;
    ULONG64 CaptureFramesDelivered;
    ULONG64 UsbUnderruns;
    ULONG64 UsbOverruns;
} OPENA8DJ_STREAM_STATE, *POPENA8DJ_STREAM_STATE;

#ifdef __cplusplus
}
#endif
