#pragma once

#ifdef __cplusplus
extern "C" {
#endif

#ifndef OPENA8DJ_CTL_BASE
#define OPENA8DJ_CTL_BASE 0x800
#endif

#define OPENA8DJ_DRIVER_API_VERSION 44

#define OPENA8DJ_VENDOR_ID 0x17CC
#define OPENA8DJ_PRODUCT_ID 0x1978

#define OPENA8DJ_INPUT_CHANNELS 8
#define OPENA8DJ_OUTPUT_CHANNELS 8
#define OPENA8DJ_STEREO_PAIRS 4
#define OPENA8DJ_SAMPLE_RATE_COUNT 4
#define OPENA8DJ_STABLE_SAMPLE_RATE_COUNT 2
#define OPENA8DJ_CHANNEL_NAME_LENGTH 32
#define OPENA8DJ_SURFACE_NAME_LENGTH 64
#define OPENA8DJ_ENDPOINT_NAME_LENGTH 64
#define OPENA8DJ_TOTAL_CHANNELS (OPENA8DJ_INPUT_CHANNELS + OPENA8DJ_OUTPUT_CHANNELS)

#define OPENA8DJ_DEFAULT_SAMPLE_RATE 48000
#define OPENA8DJ_DEFAULT_BUFFER_FRAMES 512
#define OPENA8DJ_MIN_BUFFER_FRAMES 15
#define OPENA8DJ_MAX_BUFFER_FRAMES 4096

#define OPENA8DJ_PROFILE_TIMECODE_VINYL 0
#define OPENA8DJ_PROFILE_TIMECODE_CD_LINE 1
#define OPENA8DJ_PROFILE_PHONO 2
#define OPENA8DJ_PROFILE_UNLOCK 3

#define OPENA8DJ_COMPONENT_ABSENT 0
#define OPENA8DJ_COMPONENT_PLANNED 1
#define OPENA8DJ_COMPONENT_STUB 2
#define OPENA8DJ_COMPONENT_READY 3

#define OPENA8DJ_ENDPOINT_MODEL_NONE 0
#define OPENA8DJ_ENDPOINT_MODEL_SINGLE_8CH 1
#define OPENA8DJ_ENDPOINT_MODEL_FOUR_STEREO_PAIRS 2
#define OPENA8DJ_ENDPOINT_MODEL_DUAL_PROTOTYPE 3
#define OPENA8DJ_ENDPOINT_MODEL_PRIMARY_8CH_PLUS_STEREO 4

#define OPENA8DJ_CHANNEL_DIRECTION_RENDER 0
#define OPENA8DJ_CHANNEL_DIRECTION_CAPTURE 1

#define OPENA8DJ_RATE_FLAG_44100 0x00000001u
#define OPENA8DJ_RATE_FLAG_48000 0x00000002u
#define OPENA8DJ_RATE_FLAG_88200 0x00000004u
#define OPENA8DJ_RATE_FLAG_96000 0x00000008u

#define OPENA8DJ_SURFACE_FLAG_USB_TRANSPORT 0x00000001u
#define OPENA8DJ_SURFACE_FLAG_CONTROLS 0x00000002u
#define OPENA8DJ_SURFACE_FLAG_AUDIO_ENDPOINTS 0x00000004u
#define OPENA8DJ_SURFACE_FLAG_ISOCHRONOUS_ENGINE 0x00000008u
#define OPENA8DJ_SURFACE_FLAG_MIDI 0x00000010u
#define OPENA8DJ_SURFACE_FLAG_ASIO 0x00000020u
#define OPENA8DJ_SURFACE_FLAG_EXPERIMENTAL 0x80000000u

DEFINE_GUID(GUID_DEVINTERFACE_OPENA8DJ_USB,
    0xa3ca3315, 0x46ee, 0x416b, 0xbe, 0x25, 0xfb, 0x52, 0xf3, 0xd8, 0x44, 0x22);

#define IOCTL_OPENA8DJ_GET_USB_INFO \
    CTL_CODE(FILE_DEVICE_UNKNOWN, OPENA8DJ_CTL_BASE + 0, METHOD_BUFFERED, FILE_READ_DATA)
#define IOCTL_OPENA8DJ_GET_CAPABILITIES \
    CTL_CODE(FILE_DEVICE_UNKNOWN, OPENA8DJ_CTL_BASE + 1, METHOD_BUFFERED, FILE_READ_DATA)
#define IOCTL_OPENA8DJ_GET_CONTROL_STATE \
    CTL_CODE(FILE_DEVICE_UNKNOWN, OPENA8DJ_CTL_BASE + 2, METHOD_BUFFERED, FILE_READ_DATA)
#define IOCTL_OPENA8DJ_SET_CONTROL_STATE \
    CTL_CODE(FILE_DEVICE_UNKNOWN, OPENA8DJ_CTL_BASE + 3, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_OPENA8DJ_APPLY_PROFILE \
    CTL_CODE(FILE_DEVICE_UNKNOWN, OPENA8DJ_CTL_BASE + 4, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_OPENA8DJ_GET_AUDIO_FORMAT \
    CTL_CODE(FILE_DEVICE_UNKNOWN, OPENA8DJ_CTL_BASE + 5, METHOD_BUFFERED, FILE_READ_DATA)
#define IOCTL_OPENA8DJ_SET_AUDIO_FORMAT \
    CTL_CODE(FILE_DEVICE_UNKNOWN, OPENA8DJ_CTL_BASE + 6, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_OPENA8DJ_START_STREAMING \
    CTL_CODE(FILE_DEVICE_UNKNOWN, OPENA8DJ_CTL_BASE + 7, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_OPENA8DJ_STOP_STREAMING \
    CTL_CODE(FILE_DEVICE_UNKNOWN, OPENA8DJ_CTL_BASE + 8, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_OPENA8DJ_GET_STREAM_STATE \
    CTL_CODE(FILE_DEVICE_UNKNOWN, OPENA8DJ_CTL_BASE + 9, METHOD_BUFFERED, FILE_READ_DATA)
#define IOCTL_OPENA8DJ_GET_SURFACE \
    CTL_CODE(FILE_DEVICE_UNKNOWN, OPENA8DJ_CTL_BASE + 10, METHOD_BUFFERED, FILE_READ_DATA)
#define IOCTL_OPENA8DJ_GET_TOPOLOGY \
    CTL_CODE(FILE_DEVICE_UNKNOWN, OPENA8DJ_CTL_BASE + 11, METHOD_BUFFERED, FILE_READ_DATA)
#define IOCTL_OPENA8DJ_GET_DIAGNOSTICS \
    CTL_CODE(FILE_DEVICE_UNKNOWN, OPENA8DJ_CTL_BASE + 12, METHOD_BUFFERED, FILE_READ_DATA)
#define IOCTL_OPENA8DJ_ISO_CAPTURE_SNAPSHOT \
    CTL_CODE(FILE_DEVICE_UNKNOWN, OPENA8DJ_CTL_BASE + 13, METHOD_BUFFERED, FILE_READ_DATA)
#define IOCTL_OPENA8DJ_ISO_SILENCE_PULSE \
    CTL_CODE(FILE_DEVICE_UNKNOWN, OPENA8DJ_CTL_BASE + 14, METHOD_BUFFERED, FILE_READ_DATA)
#define IOCTL_OPENA8DJ_APPLY_AUDIO_PARAMS \
    CTL_CODE(FILE_DEVICE_UNKNOWN, OPENA8DJ_CTL_BASE + 15, METHOD_BUFFERED, FILE_READ_DATA)
#define IOCTL_OPENA8DJ_ISO_TONE_BURST \
    CTL_CODE(FILE_DEVICE_UNKNOWN, OPENA8DJ_CTL_BASE + 16, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_OPENA8DJ_GET_RENDER_TRACE \
    CTL_CODE(FILE_DEVICE_UNKNOWN, OPENA8DJ_CTL_BASE + 17, METHOD_BUFFERED, FILE_READ_DATA)
#define IOCTL_OPENA8DJ_GET_USB_PLAYBACK_TRACE \
    CTL_CODE(FILE_DEVICE_UNKNOWN, OPENA8DJ_CTL_BASE + 18, METHOD_BUFFERED, FILE_READ_DATA)
#define IOCTL_OPENA8DJ_ARM_PHYSICAL_CANARY \
    CTL_CODE(FILE_DEVICE_UNKNOWN, OPENA8DJ_CTL_BASE + 19, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_OPENA8DJ_GET_SAFETY_STATE \
    CTL_CODE(FILE_DEVICE_UNKNOWN, OPENA8DJ_CTL_BASE + 20, METHOD_BUFFERED, FILE_READ_DATA)
#define IOCTL_OPENA8DJ_DISARM_PHYSICAL_CANARY \
    CTL_CODE(FILE_DEVICE_UNKNOWN, OPENA8DJ_CTL_BASE + 21, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)

#define OPENA8DJ_CANARY_PHASE_NONE 0u
#define OPENA8DJ_CANARY_PHASE_CONTROL_READ 1u
#define OPENA8DJ_CANARY_PHASE_ISO_CAPTURE 2u
#define OPENA8DJ_CANARY_PHASE_ISO_OUTPUT 3u
#define OPENA8DJ_CANARY_PHASE_STREAMING 4u
#define OPENA8DJ_CANARY_PHASE_MAX OPENA8DJ_CANARY_PHASE_STREAMING

#define OPENA8DJ_CHECKPOINT_DRIVER_LOADED 100u
#define OPENA8DJ_CHECKPOINT_PREPARE_ENTER 110u
#define OPENA8DJ_CHECKPOINT_PREPARE_SAFE 119u
#define OPENA8DJ_CHECKPOINT_CANARY_ARMED 200u
#define OPENA8DJ_CHECKPOINT_CANARY_CONSUMED 210u
#define OPENA8DJ_CHECKPOINT_ISO_CAPTURE_REQUEST_CREATED 290u
#define OPENA8DJ_CHECKPOINT_ISO_CAPTURE_BUFFER_CREATED 291u
#define OPENA8DJ_CHECKPOINT_ISO_CAPTURE_URB_CREATED 292u
#define OPENA8DJ_CHECKPOINT_ISO_CAPTURE_FORMATTED 299u
#define OPENA8DJ_CHECKPOINT_ISO_CAPTURE_SUBMIT 300u
#define OPENA8DJ_CHECKPOINT_ISO_CAPTURE_COMPLETE 301u
#define OPENA8DJ_CHECKPOINT_ISO_CAPTURE_RECLAIM_START 302u
#define OPENA8DJ_CHECKPOINT_ISO_CAPTURE_RECLAIM_COMPLETE 303u
#define OPENA8DJ_CHECKPOINT_ISO_CAPTURE_SLOT_IDLE 304u
#define OPENA8DJ_CHECKPOINT_ISO_OUTPUT_SUBMIT 310u
#define OPENA8DJ_CHECKPOINT_ISO_OUTPUT_COMPLETE 311u
#define OPENA8DJ_CHECKPOINT_ISO_OUTPUT_RECLAIM_START 312u
#define OPENA8DJ_CHECKPOINT_ISO_OUTPUT_RECLAIM_COMPLETE 313u
#define OPENA8DJ_CHECKPOINT_ISO_OUTPUT_SLOT_IDLE 314u
#define OPENA8DJ_CHECKPOINT_ISO_TIMEOUT 390u
#define OPENA8DJ_CHECKPOINT_AUDIO_RATE_SETTLE_START 370u
#define OPENA8DJ_CHECKPOINT_AUDIO_RATE_SETTLE_COMPLETE 379u
#define OPENA8DJ_CHECKPOINT_ISO_FRAME_QUERY_START 380u
#define OPENA8DJ_CHECKPOINT_ISO_FRAME_QUERY_COMPLETE 381u
#define OPENA8DJ_CHECKPOINT_STREAM_WORKER_ENTER 400u
#define OPENA8DJ_CHECKPOINT_STREAM_WORKER_EXIT 409u
#define OPENA8DJ_CHECKPOINT_DRAIN_ENTER 500u
#define OPENA8DJ_CHECKPOINT_ISO_INPUT_RESET_START 501u
#define OPENA8DJ_CHECKPOINT_ISO_INPUT_RESET_COMPLETE 502u
#define OPENA8DJ_CHECKPOINT_ISO_OUTPUT_RESET_START 503u
#define OPENA8DJ_CHECKPOINT_ISO_OUTPUT_RESET_COMPLETE 504u
#define OPENA8DJ_CHECKPOINT_ISO_INPUT_START_ENTER 505u
#define OPENA8DJ_CHECKPOINT_ISO_INPUT_START_COMPLETE 506u
#define OPENA8DJ_CHECKPOINT_ISO_OUTPUT_START_ENTER 507u
#define OPENA8DJ_CHECKPOINT_ISO_OUTPUT_START_COMPLETE 508u
#define OPENA8DJ_CHECKPOINT_DRAIN_COMPLETE 509u
#define OPENA8DJ_CHECKPOINT_ISO_REPURGE_INPUT_ENTER 510u
#define OPENA8DJ_CHECKPOINT_ISO_REPURGE_INPUT_COMPLETE 511u
#define OPENA8DJ_CHECKPOINT_ISO_REPURGE_OUTPUT_ENTER 512u
#define OPENA8DJ_CHECKPOINT_ISO_REPURGE_OUTPUT_COMPLETE 513u
#define OPENA8DJ_CHECKPOINT_ISO_PURGE_INPUT_ENTER 514u
#define OPENA8DJ_CHECKPOINT_ISO_PURGE_INPUT_COMPLETE 515u
#define OPENA8DJ_CHECKPOINT_ISO_PURGE_OUTPUT_ENTER 516u
#define OPENA8DJ_CHECKPOINT_ISO_PURGE_OUTPUT_COMPLETE 517u

typedef struct _OPENA8DJ_CANARY_ARM_REQUEST {
    ULONG Size;
    ULONG ApiVersion;
    ULONG Phase;
    ULONG MaxOperations;
    ULONGLONG NonceHigh;
    ULONGLONG NonceLow;
} OPENA8DJ_CANARY_ARM_REQUEST, *POPENA8DJ_CANARY_ARM_REQUEST;

typedef struct _OPENA8DJ_SAFETY_STATE {
    ULONG Size;
    ULONG ApiVersion;
    ULONG ArmedPhase;
    ULONG OperationsRemaining;
    ULONGLONG NonceHigh;
    ULONGLONG NonceLow;
    ULONG LastCheckpoint;
    ULONG LastCheckpointSequence;
    ULONG LastNtStatus;
    ULONG DevicePrepared;
    ULONG DeviceStopping;
    ULONG StreamWorkerActive;
    CHAR BuildFingerprint[65];
} OPENA8DJ_SAFETY_STATE, *POPENA8DJ_SAFETY_STATE;

typedef struct _OPENA8DJ_USB_INFO {
    ULONG Size;
    USHORT VendorId;
    USHORT ProductId;
    UCHAR TotalInterfaceCount;
    UCHAR ConfiguredInterfaceCount;
    UCHAR ConfiguredPipeCount;
    UCHAR AlternateSettingCount;
    UCHAR SelectedAlternateSetting;
    ULONG Ep1ReaderConfigNtStatus;
    ULONG Ep1ReaderStartNtStatus;
    ULONG Ep1ReaderCompletions;
    ULONG Ep1ReaderZeroReads;
    ULONG Ep1ReaderBytes;
    BOOLEAN HasBulkOut;
    BOOLEAN HasBulkIn;
    BOOLEAN HasIsoIn;
    BOOLEAN HasIsoOut;
} OPENA8DJ_USB_INFO, *POPENA8DJ_USB_INFO;

#define OPENA8DJ_ISO_SNAPSHOT_PACKET_COUNT 8

typedef struct _OPENA8DJ_ISO_PACKET_SNAPSHOT {
    ULONG Offset;
    ULONG RequestedLength;
    ULONG CompletedLength;
    ULONG UsbdStatus;
} OPENA8DJ_ISO_PACKET_SNAPSHOT, *POPENA8DJ_ISO_PACKET_SNAPSHOT;

typedef struct _OPENA8DJ_ISO_CAPTURE_SNAPSHOT {
    ULONG Size;
    ULONG NtStatus;
    ULONG TransferBufferLength;
    ULONG ErrorCount;
    ULONG PacketCount;
    ULONG MaximumPacketSize;
    OPENA8DJ_ISO_PACKET_SNAPSHOT Packets[OPENA8DJ_ISO_SNAPSHOT_PACKET_COUNT];
    UCHAR FirstBytes[32];
} OPENA8DJ_ISO_CAPTURE_SNAPSHOT, *POPENA8DJ_ISO_CAPTURE_SNAPSHOT;

typedef struct _OPENA8DJ_ISO_SILENCE_PULSE {
    ULONG Size;
    ULONG NtStatus;
    ULONG PlaybackNtStatus;
    ULONG PlaybackErrorCount;
    ULONG PlaybackTransferBufferLength;
    OPENA8DJ_ISO_CAPTURE_SNAPSHOT Capture;
} OPENA8DJ_ISO_SILENCE_PULSE, *POPENA8DJ_ISO_SILENCE_PULSE;

typedef struct _OPENA8DJ_ISO_TONE_BURST {
    ULONG Size;
    ULONG RequestedTransfers;
    ULONG CompletedTransfers;
    ULONG PairIndex;
    ULONG AmplitudeQ15;
    ULONG PacketBytes;
    ULONG PeriodSamples;
    ULONG NtStatus;
    ULONG FirstCaptureNtStatus;
    ULONG FirstPlaybackNtStatus;
    ULONG LastCaptureNtStatus;
    ULONG LastPlaybackNtStatus;
    ULONG CaptureErrorCount;
    ULONG PlaybackErrorCount;
    ULONG PlaybackBytes;
    OPENA8DJ_ISO_CAPTURE_SNAPSHOT LastCapture;
} OPENA8DJ_ISO_TONE_BURST, *POPENA8DJ_ISO_TONE_BURST;

typedef struct _OPENA8DJ_AUDIO_PARAMS_RESULT {
    ULONG Size;
    ULONG SampleRate;
    UCHAR RateCode;
    UCHAR Depth;
    USHORT BytesPerPacket;
    ULONG DeviceInfoWriteNtStatus;
    ULONG DeviceInfoReadNtStatus;
    ULONG DeviceInfoReplyLength;
    UCHAR DeviceInfoReply[512];
    ULONG ResetWriteNtStatus;
    ULONG ResetReadNtStatus;
    ULONG ResetNtStatus;
    ULONG SetNtStatus;
    ULONG SetWriteNtStatus;
    ULONG SetReadNtStatus;
    ULONG ResetReplyLength;
    ULONG SetReplyLength;
    UCHAR ResetReply[512];
    UCHAR SetReply[512];
} OPENA8DJ_AUDIO_PARAMS_RESULT, *POPENA8DJ_AUDIO_PARAMS_RESULT;

typedef struct _OPENA8DJ_CAPABILITIES {
    ULONG Size;
    ULONG ApiVersion;
    USHORT VendorId;
    USHORT ProductId;
    UCHAR InputChannels;
    UCHAR OutputChannels;
    UCHAR StereoPairs;
    UCHAR MidiInputs;
    UCHAR MidiOutputs;
    ULONG SampleRates[OPENA8DJ_SAMPLE_RATE_COUNT];
    ULONG MinBufferFrames;
    ULONG MaxBufferFrames;
    ULONG DefaultBufferFrames;
    CHAR InputPairNames[OPENA8DJ_STEREO_PAIRS][OPENA8DJ_CHANNEL_NAME_LENGTH];
    CHAR OutputPairNames[OPENA8DJ_STEREO_PAIRS][OPENA8DJ_CHANNEL_NAME_LENGTH];
    BOOLEAN Experimental;
    BOOLEAN WindowsAudioEndpointExposed;
    BOOLEAN UsbTransportReady;
    BOOLEAN MidiReady;
    BOOLEAN ControlsReady;
} OPENA8DJ_CAPABILITIES, *POPENA8DJ_CAPABILITIES;

typedef struct _OPENA8DJ_WINDOWS_SURFACE {
    ULONG Size;
    ULONG ApiVersion;
    ULONG SurfaceFlags;
    ULONG StableSampleRateFlags;
    ULONG PlannedSampleRateFlags;
    ULONG AudioEndpointState;
    ULONG UsbTransportState;
    ULONG IsochronousEngineState;
    ULONG MidiState;
    ULONG ControlState;
    ULONG AsioState;
    ULONG EndpointModel;
    CHAR DriverModel[OPENA8DJ_SURFACE_NAME_LENGTH];
    CHAR AudioModel[OPENA8DJ_SURFACE_NAME_LENGTH];
    CHAR StreamingModel[OPENA8DJ_SURFACE_NAME_LENGTH];
    CHAR SafetyPolicy[OPENA8DJ_SURFACE_NAME_LENGTH];
} OPENA8DJ_WINDOWS_SURFACE, *POPENA8DJ_WINDOWS_SURFACE;

typedef struct _OPENA8DJ_CHANNEL_DESCRIPTOR {
    ULONG Size;
    ULONG Direction;
    ULONG ChannelIndex;
    ULONG PairIndex;
    ULONG PairChannelIndex;
    CHAR Name[OPENA8DJ_CHANNEL_NAME_LENGTH];
} OPENA8DJ_CHANNEL_DESCRIPTOR, *POPENA8DJ_CHANNEL_DESCRIPTOR;

typedef struct _OPENA8DJ_TOPOLOGY {
    ULONG Size;
    ULONG ApiVersion;
    ULONG EndpointModel;
    ULONG RenderEndpointCount;
    ULONG CaptureEndpointCount;
    ULONG RenderChannelCount;
    ULONG CaptureChannelCount;
    CHAR RenderEndpointName[OPENA8DJ_ENDPOINT_NAME_LENGTH];
    CHAR CaptureEndpointName[OPENA8DJ_ENDPOINT_NAME_LENGTH];
    OPENA8DJ_CHANNEL_DESCRIPTOR Channels[OPENA8DJ_TOTAL_CHANNELS];
} OPENA8DJ_TOPOLOGY, *POPENA8DJ_TOPOLOGY;

typedef struct _OPENA8DJ_CONTROL_STATE {
    ULONG Size;
    UCHAR InputMode;
    UCHAR GndLiftTCVinyl;
    UCHAR GndLiftTCCDLine;
    UCHAR GndLiftPhono;
    UCHAR SoftwareLock;
} OPENA8DJ_CONTROL_STATE, *POPENA8DJ_CONTROL_STATE;

typedef struct _OPENA8DJ_PROFILE_REQUEST {
    ULONG Size;
    ULONG Profile;
} OPENA8DJ_PROFILE_REQUEST, *POPENA8DJ_PROFILE_REQUEST;

typedef struct _OPENA8DJ_AUDIO_FORMAT {
    ULONG Size;
    ULONG SampleRate;
    ULONG InputChannels;
    ULONG OutputChannels;
    ULONG BufferFrames;
} OPENA8DJ_AUDIO_FORMAT, *POPENA8DJ_AUDIO_FORMAT;

typedef struct _OPENA8DJ_STREAM_STATE {
    ULONG Size;
    BOOLEAN Streaming;
    BOOLEAN StreamingEngineReady;
    ULONG SampleRate;
    ULONG BufferFrames;
    ULONG64 RenderFramesSubmitted;
    ULONG64 CaptureFramesDelivered;
    ULONG64 UsbUnderruns;
    ULONG64 UsbOverruns;
    ULONG64 UsbInPacketsCompleted;
    ULONG64 UsbOutPacketsCompleted;
    ULONG64 UsbPacketErrors;
    ULONG64 LateCompletions;
} OPENA8DJ_STREAM_STATE, *POPENA8DJ_STREAM_STATE;

typedef struct _OPENA8DJ_DIAGNOSTICS {
    ULONG Size;
    ULONG ApiVersion;
    ULONG64 StartRequests;
    ULONG64 RejectedStartRequests;
    ULONG64 StopRequests;
    ULONG64 FormatChanges;
    ULONG64 ControlWrites;
    ULONG64 ProfileApplies;
    BOOLEAN ControlsHardwareReady;
    BOOLEAN LastControlWriteMismatch;
    UCHAR RawControlState[6];
    UCHAR LastControlWriteRequest[6];
    UCHAR LastControlWriteReadBack[6];
    ULONG LastControlReadNtStatus;
    ULONG LastControlWriteNtStatus;
    ULONG LastControlReadbackNtStatus;
    OPENA8DJ_STREAM_STATE StreamState;
    ULONG64 AcxCreateStreamCallbacks;
    ULONG64 AcxPrepareCallbacks;
    ULONG64 AcxReleaseCallbacks;
    ULONG64 AcxRunCallbacks;
    ULONG64 AcxPauseCallbacks;
    ULONG64 AcxLatencyCallbacks;
    ULONG64 AcxAllocatePacketCallbacks;
    ULONG64 AcxFreePacketCallbacks;
    ULONG64 AcxSetRenderPacketCallbacks;
    ULONG64 AcxGetCurrentPacketCallbacks;
    ULONG64 AcxGetCapturePacketCallbacks;
    ULONG64 AcxGetPresentationPositionCallbacks;
    ULONG64 AcxRtFramesRead;
    ULONG64 AcxRtNonZeroFrames;
    ULONG AcxRtPeakAbsS24;
    ULONG64 AcxRtRenderPairNonZeroFrames[OPENA8DJ_STEREO_PAIRS];
    ULONG AcxRtRenderPairPeakAbsS24[OPENA8DJ_STEREO_PAIRS];
    ULONG64 AcxRtCapturePairNonZeroFrames[OPENA8DJ_STEREO_PAIRS];
    ULONG AcxRtCapturePairPeakAbsS16[OPENA8DJ_STEREO_PAIRS];
    ULONG AcxRtChannels;
    ULONG AcxRtBlockAlign;
    ULONG AcxRtBitsPerSample;
    ULONG AcxRtIsFloat;
    ULONG AcxRtPacketCount;
    ULONG AcxRtPacketSize;
    ULONG AcxRtFrameCount;
    ULONG AcxLastSetRenderPacket;
    ULONG AcxLastSetRenderFlags;
    ULONG AcxLastSetRenderEosPacketLength;
    ULONG64 AcxRtRenderPacketCompletions;
    ULONG64 AcxRtRenderPacketNotifications;
    ULONG64 AcxRtRenderPacketNotificationFailures;
    ULONG AcxRtRenderCurrentPacket;
    ULONG AcxRtRenderLastNotificationNtStatus;
    ULONG64 StreamWorkerIterations;
    ULONG64 StreamWorkerCaptureBytes;
    ULONG64 StreamWorkerPlaybackBytes;
    ULONG64 StreamWorkerNoRenderIterations;
    ULONG StreamWorkerLastCaptureBytes;
    ULONG StreamWorkerLastPlaybackBytes;
    ULONG StreamWorkerLastRenderMask;
    ULONG StreamWorkerLastCaptureMask;
    ULONG StreamWorkerMaxCaptureBytes;
    ULONG StreamWorkerMaxPlaybackBytes;
    ULONG PersistentIsoPacketCount;
    ULONG PersistentIsoSlotCount;
    ULONG PersistentIsoOutputLeadFrames;
    ULONG64 IsoQpcFrequency;
    ULONG64 IsoOutputQueueEmptyTransitions;
    ULONG64 IsoOutputLatePackets;
    ULONG64 IsoOutputBadStartFrames;
    ULONG64 IsoOutputOtherPacketErrors;
    ULONG64 IsoOutputPanicFlags;
    ULONG64 IsoCaptureLatePackets;
    ULONG64 IsoCaptureBadStartFrames;
    ULONG64 IsoCaptureOtherPacketErrors;
    ULONG IsoLastCaptureUrbStatus;
    ULONG IsoLastCapturePacketStatus;
    ULONG IsoLastCaptureErrorCount;
    ULONG64 IsoCaptureToOutputSubmitMaxQpc;
    ULONG IsoLastCaptureStartFrame;
    ULONG IsoLastOutputStartFrame;
    ULONG64 AudioRateSettleRuns;
    ULONG64 AudioRateSettleSnapshots;
    ULONG64 AudioRateSettleMismatchedPackets;
    ULONG64 AudioRateSettleFailures;
    ULONG AudioRateSettleLastObservedBytes;
    ULONG64 IsoCaptureFrameQueries;
    ULONG64 IsoCaptureFrameQueryFailures;
    ULONG IsoCaptureFrameQueryCurrent;
    ULONG IsoCaptureSeedStartFrame;
    ULONG IsoCaptureNextStartFrame;
    ULONG IsoCaptureErrorSnapshotSequence;
    ULONG IsoLastCaptureErrorSlot;
    LONG IsoLastCaptureErrorGeneration;
    ULONG64 IsoLastCaptureErrorSubmitSequence;
    ULONG IsoLastCaptureErrorScheduledStartFrame;
    ULONG IsoLastCaptureErrorFirstPacket;
    ULONG IsoLastCaptureErrorLastPacket;
    ULONG IsoLastCaptureErrorPacketCount;
    ULONG64 IsoLastCaptureErrorSubmitQpc;
    ULONG64 IsoLastCaptureErrorCompletionQpc;
    ULONG64 IsoInputPipeResetRuns;
    ULONG64 IsoInputPipeResetFailures;
    ULONG IsoInputPipeResetLastNtStatus;
    ULONG64 IsoOutputPipeResetRuns;
    ULONG64 IsoOutputPipeResetFailures;
    ULONG IsoOutputPipeResetLastNtStatus;
    ULONG IsoOneShotActive;
    ULONG IsoTransportHealthy;
    LONG IsoTransportHealthyGeneration;
    ULONG IsoInputTargetStartLastNtStatus;
    ULONG IsoOutputTargetStartLastNtStatus;
} OPENA8DJ_DIAGNOSTICS, *POPENA8DJ_DIAGNOSTICS;

#define OPENA8DJ_RENDER_TRACE_FRAME_COUNT 256

typedef struct _OPENA8DJ_RENDER_TRACE_FRAME {
    ULONG PairIndex;
    ULONG RtChannels;
    ULONG RtBlockAlign;
    ULONG RtBitsPerSample;
    ULONG RtFrameCursor;
    ULONG RtFrameCount;
    ULONG OutputByteInFrame;
    ULONGLONG PositionBlocks;
    LONG RawLeftS24;
    LONG RawRightS24;
    LONG OutputLeftS24;
    LONG OutputRightS24;
} OPENA8DJ_RENDER_TRACE_FRAME, *POPENA8DJ_RENDER_TRACE_FRAME;

typedef struct _OPENA8DJ_RENDER_TRACE {
    ULONG Size;
    ULONG FrameCount;
    ULONG WriteIndex;
    ULONG ActiveRenderMask;
    ULONG RtChannels;
    ULONG RtBlockAlign;
    ULONG RtBitsPerSample;
    ULONG RtFrameCount;
    ULONG64 WriteCount;
    OPENA8DJ_RENDER_TRACE_FRAME Frames[OPENA8DJ_RENDER_TRACE_FRAME_COUNT];
} OPENA8DJ_RENDER_TRACE, *POPENA8DJ_RENDER_TRACE;

#define OPENA8DJ_USB_PLAYBACK_TRACE_BYTES 65536

typedef struct _OPENA8DJ_USB_PLAYBACK_TRACE {
    ULONG Size;
    ULONG ByteCount;
    ULONG FixedPacketBytes;
    ULONG ActiveRenderMask;
    ULONG WorkerLastPlaybackBytes;
    ULONG64 WorkerIteration;
    UCHAR Bytes[OPENA8DJ_USB_PLAYBACK_TRACE_BYTES];
} OPENA8DJ_USB_PLAYBACK_TRACE, *POPENA8DJ_USB_PLAYBACK_TRACE;

#ifdef __cplusplus
}
#endif
